// THIS FILE WAS AUTOMATICALLY GENERATED BY A TOOL.
// EDITING THIS FILE MAY CAUSE SIDE EFFECTS.
// DO SO AT YOUR OWN RISK.

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#include "double2.h"


typedef struct double3x2
{
	double2 rows[3];
} double3x2;

#ifdef __cplusplus
}
#endif
