// This file was automatically generated by HLML v3.0.0.
// Editing this file may cause side effects.

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#include "float3.h"


typedef struct float2x3
{
	float3 rows[2];
} float2x3;

#ifdef __cplusplus
}
#endif
