/*
===========================================================================

HLML.

MIT License

Copyright (c) 2019 Dan Moody

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

===========================================================================
*/

// THIS FILE WAS AUTOMATICALLY GENERATED BY A TOOL.
// EDITING THIS FILE MAY CAUSE SIDE EFFECTS.
// DO SO AT YOUR OWN RISK.

TEMPER_PARAMETRIC( Test_double4x2_less_than, TEMPER_FLAG_SHOULD_RUN, const double4x2& lhs, const double4x2& rhs, const bool4x2& expectedAnswer )
{
	bool4x2 actualResult = lhs < rhs;
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_less_than,
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	),
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	),
	bool4x2(
		false, false,
		false, false,
		false, false,
		false, false
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_less_than,
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	),
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	bool4x2(
		true, true,
		true, true,
		true, true,
		true, true
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_less_than,
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	bool4x2(
		false, false,
		false, false,
		false, false,
		false, false
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_less_than,
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	),
	bool4x2(
		false, false,
		false, false,
		false, false,
		false, false
	)
);

TEMPER_PARAMETRIC( Test_double4x2_less_than_equal, TEMPER_FLAG_SHOULD_RUN, const double4x2& lhs, const double4x2& rhs, const bool4x2& expectedAnswer )
{
	bool4x2 actualResult = lhs <= rhs;
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_less_than_equal,
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	),
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	),
	bool4x2(
		true, true,
		true, true,
		true, true,
		true, true
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_less_than_equal,
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	),
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	bool4x2(
		true, true,
		true, true,
		true, true,
		true, true
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_less_than_equal,
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	bool4x2(
		true, true,
		true, true,
		true, true,
		true, true
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_less_than_equal,
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	),
	bool4x2(
		false, false,
		false, false,
		false, false,
		false, false
	)
);

TEMPER_PARAMETRIC( Test_double4x2_greater_than, TEMPER_FLAG_SHOULD_RUN, const double4x2& lhs, const double4x2& rhs, const bool4x2& expectedAnswer )
{
	bool4x2 actualResult = lhs > rhs;
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_greater_than,
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	),
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	),
	bool4x2(
		false, false,
		false, false,
		false, false,
		false, false
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_greater_than,
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	),
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	bool4x2(
		false, false,
		false, false,
		false, false,
		false, false
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_greater_than,
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	bool4x2(
		false, false,
		false, false,
		false, false,
		false, false
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_greater_than,
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	),
	bool4x2(
		true, true,
		true, true,
		true, true,
		true, true
	)
);

TEMPER_PARAMETRIC( Test_double4x2_greater_than_equal, TEMPER_FLAG_SHOULD_RUN, const double4x2& lhs, const double4x2& rhs, const bool4x2& expectedAnswer )
{
	bool4x2 actualResult = lhs >= rhs;
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_greater_than_equal,
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	),
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	),
	bool4x2(
		true, true,
		true, true,
		true, true,
		true, true
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_greater_than_equal,
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	),
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	bool4x2(
		false, false,
		false, false,
		false, false,
		false, false
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_greater_than_equal,
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	bool4x2(
		true, true,
		true, true,
		true, true,
		true, true
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_greater_than_equal,
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	),
	bool4x2(
		true, true,
		true, true,
		true, true,
		true, true
	)
);

TEMPER_PARAMETRIC( Test_double4x2_cadds, TEMPER_FLAG_SHOULD_RUN, const double4x2& lhs, const double& rhs, const double4x2& expectedAnswer )
{
	double4x2 actualResult = lhs + rhs;
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_cadds,
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	1.000000f,
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_cadds,
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	),
	2.000000f,
	double4x2(
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_cadds,
	double4x2(
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f
	),
	2.000000f,
	double4x2(
		6.000000f, 6.000000f,
		6.000000f, 6.000000f,
		6.000000f, 6.000000f,
		6.000000f, 6.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_cadds,
	double4x2(
		8.000000f, 8.000000f,
		8.000000f, 8.000000f,
		8.000000f, 8.000000f,
		8.000000f, 8.000000f
	),
	4.000000f,
	double4x2(
		12.000000f, 12.000000f,
		12.000000f, 12.000000f,
		12.000000f, 12.000000f,
		12.000000f, 12.000000f
	)
);

TEMPER_PARAMETRIC( Test_double4x2_csubs, TEMPER_FLAG_SHOULD_RUN, const double4x2& lhs, const double& rhs, const double4x2& expectedAnswer )
{
	double4x2 actualResult = lhs - rhs;
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_csubs,
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	1.000000f,
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_csubs,
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	),
	2.000000f,
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_csubs,
	double4x2(
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f
	),
	2.000000f,
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_csubs,
	double4x2(
		8.000000f, 8.000000f,
		8.000000f, 8.000000f,
		8.000000f, 8.000000f,
		8.000000f, 8.000000f
	),
	4.000000f,
	double4x2(
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f
	)
);

TEMPER_PARAMETRIC( Test_double4x2_cmuls, TEMPER_FLAG_SHOULD_RUN, const double4x2& lhs, const double& rhs, const double4x2& expectedAnswer )
{
	double4x2 actualResult = lhs * rhs;
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_cmuls,
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	1.000000f,
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_cmuls,
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	),
	2.000000f,
	double4x2(
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_cmuls,
	double4x2(
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f
	),
	2.000000f,
	double4x2(
		8.000000f, 8.000000f,
		8.000000f, 8.000000f,
		8.000000f, 8.000000f,
		8.000000f, 8.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_cmuls,
	double4x2(
		8.000000f, 8.000000f,
		8.000000f, 8.000000f,
		8.000000f, 8.000000f,
		8.000000f, 8.000000f
	),
	4.000000f,
	double4x2(
		32.000000f, 32.000000f,
		32.000000f, 32.000000f,
		32.000000f, 32.000000f,
		32.000000f, 32.000000f
	)
);

TEMPER_PARAMETRIC( Test_double4x2_cdivs, TEMPER_FLAG_SHOULD_RUN, const double4x2& lhs, const double& rhs, const double4x2& expectedAnswer )
{
	double4x2 actualResult = lhs / rhs;
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_cdivs,
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	1.000000f,
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_cdivs,
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	),
	2.000000f,
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_cdivs,
	double4x2(
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f
	),
	2.000000f,
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_cdivs,
	double4x2(
		8.000000f, 8.000000f,
		8.000000f, 8.000000f,
		8.000000f, 8.000000f,
		8.000000f, 8.000000f
	),
	4.000000f,
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	)
);

TEMPER_PARAMETRIC( Test_double4x2_caddm, TEMPER_FLAG_SHOULD_RUN, const double4x2& lhs, const double4x2& rhs, const double4x2& expectedAnswer )
{
	double4x2 actualResult = lhs + rhs;
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_caddm,
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_caddm,
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	),
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	),
	double4x2(
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_caddm,
	double4x2(
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f
	),
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	),
	double4x2(
		6.000000f, 6.000000f,
		6.000000f, 6.000000f,
		6.000000f, 6.000000f,
		6.000000f, 6.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_caddm,
	double4x2(
		8.000000f, 8.000000f,
		8.000000f, 8.000000f,
		8.000000f, 8.000000f,
		8.000000f, 8.000000f
	),
	double4x2(
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f
	),
	double4x2(
		12.000000f, 12.000000f,
		12.000000f, 12.000000f,
		12.000000f, 12.000000f,
		12.000000f, 12.000000f
	)
);

TEMPER_PARAMETRIC( Test_double4x2_csubm, TEMPER_FLAG_SHOULD_RUN, const double4x2& lhs, const double4x2& rhs, const double4x2& expectedAnswer )
{
	double4x2 actualResult = lhs - rhs;
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_csubm,
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_csubm,
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	),
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	),
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_csubm,
	double4x2(
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f
	),
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	),
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_csubm,
	double4x2(
		8.000000f, 8.000000f,
		8.000000f, 8.000000f,
		8.000000f, 8.000000f,
		8.000000f, 8.000000f
	),
	double4x2(
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f
	),
	double4x2(
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f
	)
);

TEMPER_PARAMETRIC( Test_double4x2_cmulm, TEMPER_FLAG_SHOULD_RUN, const double4x2& lhs, const double4x2& rhs, const double4x2& expectedAnswer )
{
	double4x2 actualResult = lhs * rhs;
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_cmulm,
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_cmulm,
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	),
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	),
	double4x2(
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_cmulm,
	double4x2(
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f
	),
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	),
	double4x2(
		8.000000f, 8.000000f,
		8.000000f, 8.000000f,
		8.000000f, 8.000000f,
		8.000000f, 8.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_cmulm,
	double4x2(
		8.000000f, 8.000000f,
		8.000000f, 8.000000f,
		8.000000f, 8.000000f,
		8.000000f, 8.000000f
	),
	double4x2(
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f
	),
	double4x2(
		32.000000f, 32.000000f,
		32.000000f, 32.000000f,
		32.000000f, 32.000000f,
		32.000000f, 32.000000f
	)
);

TEMPER_PARAMETRIC( Test_double4x2_cdivm, TEMPER_FLAG_SHOULD_RUN, const double4x2& lhs, const double4x2& rhs, const double4x2& expectedAnswer )
{
	double4x2 actualResult = lhs / rhs;
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_cdivm,
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_cdivm,
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	),
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	),
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_cdivm,
	double4x2(
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f
	),
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	),
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_cdivm,
	double4x2(
		8.000000f, 8.000000f,
		8.000000f, 8.000000f,
		8.000000f, 8.000000f,
		8.000000f, 8.000000f
	),
	double4x2(
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f
	),
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	)
);

#if defined( __GNUC__ ) || defined( __clang__ )
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wcast-qual"
#endif

TEMPER_PARAMETRIC( Test_double4x2_increment_prefix, TEMPER_FLAG_SHOULD_RUN, const double4x2& x, const double4x2& expectedAnswer )
{
	// make local copy of x and use that because we cant do increment or decrement operations on a const reference
	// and MSVC throws warnings if we just make the parameter a non-const reference
	double4x2 xlocal = (double4x2) x;
	double4x2 actualAnswer = ++xlocal;
	TEMPER_CHECK_TRUE( actualAnswer == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_increment_prefix,
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_increment_prefix,
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	),
	double4x2(
		3.000000f, 3.000000f,
		3.000000f, 3.000000f,
		3.000000f, 3.000000f,
		3.000000f, 3.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_increment_prefix,
	double4x2(
		3.000000f, 3.000000f,
		3.000000f, 3.000000f,
		3.000000f, 3.000000f,
		3.000000f, 3.000000f
	),
	double4x2(
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_increment_prefix,
	double4x2(
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f
	),
	double4x2(
		5.000000f, 5.000000f,
		5.000000f, 5.000000f,
		5.000000f, 5.000000f,
		5.000000f, 5.000000f
	)
);

TEMPER_PARAMETRIC( Test_double4x2_increment_postfix, TEMPER_FLAG_SHOULD_RUN, const double4x2& x, const double4x2& expectedAnswer )
{
	// make local copy of x and use that because we cant do increment or decrement operations on a const reference
	// and MSVC throws warnings if we just make the parameter a non-const reference
	double4x2 xlocal = (double4x2) x;
	double4x2 actualAnswer = xlocal++;
	TEMPER_CHECK_TRUE( actualAnswer == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_increment_postfix,
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_increment_postfix,
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	),
	double4x2(
		3.000000f, 3.000000f,
		3.000000f, 3.000000f,
		3.000000f, 3.000000f,
		3.000000f, 3.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_increment_postfix,
	double4x2(
		3.000000f, 3.000000f,
		3.000000f, 3.000000f,
		3.000000f, 3.000000f,
		3.000000f, 3.000000f
	),
	double4x2(
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_increment_postfix,
	double4x2(
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f
	),
	double4x2(
		5.000000f, 5.000000f,
		5.000000f, 5.000000f,
		5.000000f, 5.000000f,
		5.000000f, 5.000000f
	)
);

TEMPER_PARAMETRIC( Test_double4x2_decrement_prefix, TEMPER_FLAG_SHOULD_RUN, const double4x2& x, const double4x2& expectedAnswer )
{
	// make local copy of x and use that because we cant do increment or decrement operations on a const reference
	// and MSVC throws warnings if we just make the parameter a non-const reference
	double4x2 xlocal = (double4x2) x;
	double4x2 actualAnswer = --xlocal;
	TEMPER_CHECK_TRUE( actualAnswer == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_decrement_prefix,
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_decrement_prefix,
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	),
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_decrement_prefix,
	double4x2(
		3.000000f, 3.000000f,
		3.000000f, 3.000000f,
		3.000000f, 3.000000f,
		3.000000f, 3.000000f
	),
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_decrement_prefix,
	double4x2(
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f
	),
	double4x2(
		3.000000f, 3.000000f,
		3.000000f, 3.000000f,
		3.000000f, 3.000000f,
		3.000000f, 3.000000f
	)
);

TEMPER_PARAMETRIC( Test_double4x2_decrement_postfix, TEMPER_FLAG_SHOULD_RUN, const double4x2& x, const double4x2& expectedAnswer )
{
	// make local copy of x and use that because we cant do increment or decrement operations on a const reference
	// and MSVC throws warnings if we just make the parameter a non-const reference
	double4x2 xlocal = (double4x2) x;
	double4x2 actualAnswer = xlocal--;
	TEMPER_CHECK_TRUE( actualAnswer == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_decrement_postfix,
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_decrement_postfix,
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	),
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_decrement_postfix,
	double4x2(
		3.000000f, 3.000000f,
		3.000000f, 3.000000f,
		3.000000f, 3.000000f,
		3.000000f, 3.000000f
	),
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_decrement_postfix,
	double4x2(
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f,
		4.000000f, 4.000000f
	),
	double4x2(
		3.000000f, 3.000000f,
		3.000000f, 3.000000f,
		3.000000f, 3.000000f,
		3.000000f, 3.000000f
	)
);

#if defined( __GNUC__ ) || defined( __clang__ )
#pragma GCC diagnostic pop
#endif
#if defined( __GNUC__ ) || defined( __clang__ )
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wcast-qual"
#endif
TEMPER_PARAMETRIC( Test_double4x2_negate_prefix, TEMPER_FLAG_SHOULD_RUN, const double4x2& x, const double4x2& expectedAnswer )
{
	// make local copy of x and use that because we cant do increment or decrement operations on a const reference
	// and MSVC throws warnings if we just make the parameter a non-const reference
	double4x2 xlocal = (double4x2) x;
	double4x2 actualAnswer = -xlocal;
	TEMPER_CHECK_TRUE( actualAnswer == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_negate_prefix,
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	),
	double4x2(
		-0.000000f, -0.000000f,
		-0.000000f, -0.000000f,
		-0.000000f, -0.000000f,
		-0.000000f, -0.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_negate_prefix,
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	double4x2(
		-1.000000f, -1.000000f,
		-1.000000f, -1.000000f,
		-1.000000f, -1.000000f,
		-1.000000f, -1.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_negate_prefix,
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	),
	double4x2(
		-2.000000f, -2.000000f,
		-2.000000f, -2.000000f,
		-2.000000f, -2.000000f,
		-2.000000f, -2.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_negate_prefix,
	double4x2(
		3.000000f, 3.000000f,
		3.000000f, 3.000000f,
		3.000000f, 3.000000f,
		3.000000f, 3.000000f
	),
	double4x2(
		-3.000000f, -3.000000f,
		-3.000000f, -3.000000f,
		-3.000000f, -3.000000f,
		-3.000000f, -3.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_negate_prefix,
	double4x2(
		10.000000f, 10.000000f,
		10.000000f, 10.000000f,
		10.000000f, 10.000000f,
		10.000000f, 10.000000f
	),
	double4x2(
		-10.000000f, -10.000000f,
		-10.000000f, -10.000000f,
		-10.000000f, -10.000000f,
		-10.000000f, -10.000000f
	)
);

#if defined( __GNUC__ ) || defined( __clang__ )
#pragma GCC diagnostic pop
#endif

TEMPER_PARAMETRIC( Test_double4x2_min, TEMPER_FLAG_SHOULD_RUN, const double4x2& lhs, const double4x2& rhs, const double4x2& expectedAnswer )
{
	double4x2 actualResult = min( lhs, rhs );
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_min,
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	),
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_min,
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	),
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_min,
	double4x2(
		420.000000f, 420.000000f,
		420.000000f, 420.000000f,
		420.000000f, 420.000000f,
		420.000000f, 420.000000f
	),
	double4x2(
		69.000000f, 69.000000f,
		69.000000f, 69.000000f,
		69.000000f, 69.000000f,
		69.000000f, 69.000000f
	),
	double4x2(
		69.000000f, 69.000000f,
		69.000000f, 69.000000f,
		69.000000f, 69.000000f,
		69.000000f, 69.000000f
	)
);

TEMPER_PARAMETRIC( Test_double4x2_max, TEMPER_FLAG_SHOULD_RUN, const double4x2& lhs, const double4x2& rhs, const double4x2& expectedAnswer )
{
	double4x2 actualResult = max( lhs, rhs );
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_max,
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	),
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_max,
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	),
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_max,
	double4x2(
		69.000000f, 69.000000f,
		69.000000f, 69.000000f,
		69.000000f, 69.000000f,
		69.000000f, 69.000000f
	),
	double4x2(
		420.000000f, 420.000000f,
		420.000000f, 420.000000f,
		420.000000f, 420.000000f,
		420.000000f, 420.000000f
	),
	double4x2(
		420.000000f, 420.000000f,
		420.000000f, 420.000000f,
		420.000000f, 420.000000f,
		420.000000f, 420.000000f
	)
);

TEMPER_PARAMETRIC( Test_double4x2_saturate, TEMPER_FLAG_SHOULD_RUN, const double4x2& x, const double4x2& expectedAnswer )
{
	double4x2 actualResult = saturate( x );
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_saturate,
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	),
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_saturate,
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_saturate,
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	),
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_saturate,
	double4x2(
		3.000000f, 3.000000f,
		3.000000f, 3.000000f,
		3.000000f, 3.000000f,
		3.000000f, 3.000000f
	),
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_saturate,
	double4x2(
		10.000000f, 10.000000f,
		10.000000f, 10.000000f,
		10.000000f, 10.000000f,
		10.000000f, 10.000000f
	),
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	)
);

TEMPER_PARAMETRIC( Test_double4x2_sign, TEMPER_FLAG_SHOULD_RUN, const double4x2& x, const int4x2& expectedAnswer )
{
	int4x2 actualResult = sign( x );
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_sign,
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	),
	int4x2(
		0, 0,
		0, 0,
		0, 0,
		0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_sign,
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	int4x2(
		1, 1,
		1, 1,
		1, 1,
		1, 1
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_sign,
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	),
	int4x2(
		1, 1,
		1, 1,
		1, 1,
		1, 1
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_sign,
	double4x2(
		3.000000f, 3.000000f,
		3.000000f, 3.000000f,
		3.000000f, 3.000000f,
		3.000000f, 3.000000f
	),
	int4x2(
		1, 1,
		1, 1,
		1, 1,
		1, 1
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_sign,
	double4x2(
		-1.000000f, -1.000000f,
		-1.000000f, -1.000000f,
		-1.000000f, -1.000000f,
		-1.000000f, -1.000000f
	),
	int4x2(
		-1, -1,
		-1, -1,
		-1, -1,
		-1, -1
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_sign,
	double4x2(
		-2.000000f, -2.000000f,
		-2.000000f, -2.000000f,
		-2.000000f, -2.000000f,
		-2.000000f, -2.000000f
	),
	int4x2(
		-1, -1,
		-1, -1,
		-1, -1,
		-1, -1
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_sign,
	double4x2(
		-3.000000f, -3.000000f,
		-3.000000f, -3.000000f,
		-3.000000f, -3.000000f,
		-3.000000f, -3.000000f
	),
	int4x2(
		-1, -1,
		-1, -1,
		-1, -1,
		-1, -1
	)
);

TEMPER_PARAMETRIC( Test_double4x2_lerp, TEMPER_FLAG_SHOULD_RUN, const double4x2& lhs, const double4x2& rhs, const double t, const double4x2& expectedAnswer )
{
	double4x2 actualResult = lerp( lhs, rhs, t );
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_lerp,
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	),
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	0.500000f,
	double4x2(
		0.500000f, 0.500000f,
		0.500000f, 0.500000f,
		0.500000f, 0.500000f,
		0.500000f, 0.500000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_lerp,
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		1.000000f, 1.000000f
	),
	double4x2(
		3.000000f, 3.000000f,
		3.000000f, 3.000000f,
		3.000000f, 3.000000f,
		3.000000f, 3.000000f
	),
	0.500000f,
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	)
);

TEMPER_PARAMETRIC( Test_double4x2_int4x2, TEMPER_FLAG_SHOULD_RUN, const int4x2& convertFrom, const double4x2& expectedAnswer )
{
	double4x2 actualAnswer = double4x2( convertFrom );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[0][0], actualAnswer[0][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[0][1], actualAnswer[0][1] ) );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[1][0], actualAnswer[1][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[1][1], actualAnswer[1][1] ) );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[2][0], actualAnswer[2][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[2][1], actualAnswer[2][1] ) );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[3][0], actualAnswer[3][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[3][1], actualAnswer[3][1] ) );

}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_int4x2,
	int4x2(
		0, 0,
		0, 0,
		0, 0,
		0, 0
	),
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_int4x2,
	int4x2(
		10, 10,
		10, 10,
		10, 10,
		10, 10
	),
	double4x2(
		10.000000f, 10.000000f,
		10.000000f, 10.000000f,
		10.000000f, 10.000000f,
		10.000000f, 10.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_int4x2,
	int4x2(
		10, 20,
		50, 60,
		90, 100,
		130, 140
	),
	double4x2(
		10.000000f, 20.000000f,
		50.000000f, 60.000000f,
		90.000000f, 100.000000f,
		130.000000f, 140.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_int4x2,
	int4x2(
		160, 150,
		120, 110,
		80, 70,
		40, 30
	),
	double4x2(
		160.000000f, 150.000000f,
		120.000000f, 110.000000f,
		80.000000f, 70.000000f,
		40.000000f, 30.000000f
	)
);

TEMPER_PARAMETRIC( Test_double4x2_int4x3, TEMPER_FLAG_SHOULD_RUN, const int4x3& convertFrom, const double4x2& expectedAnswer )
{
	double4x2 actualAnswer = double4x2( convertFrom );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[0][0], actualAnswer[0][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[0][1], actualAnswer[0][1] ) );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[1][0], actualAnswer[1][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[1][1], actualAnswer[1][1] ) );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[2][0], actualAnswer[2][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[2][1], actualAnswer[2][1] ) );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[3][0], actualAnswer[3][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[3][1], actualAnswer[3][1] ) );

}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_int4x3,
	int4x3(
		0, 0, 0,
		0, 0, 0,
		0, 0, 0,
		0, 0, 0
	),
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_int4x3,
	int4x3(
		10, 10, 10,
		10, 10, 10,
		10, 10, 10,
		10, 10, 10
	),
	double4x2(
		10.000000f, 10.000000f,
		10.000000f, 10.000000f,
		10.000000f, 10.000000f,
		10.000000f, 10.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_int4x3,
	int4x3(
		10, 20, 30,
		50, 60, 70,
		90, 100, 110,
		130, 140, 150
	),
	double4x2(
		10.000000f, 20.000000f,
		50.000000f, 60.000000f,
		90.000000f, 100.000000f,
		130.000000f, 140.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_int4x3,
	int4x3(
		160, 150, 140,
		120, 110, 100,
		80, 70, 60,
		40, 30, 20
	),
	double4x2(
		160.000000f, 150.000000f,
		120.000000f, 110.000000f,
		80.000000f, 70.000000f,
		40.000000f, 30.000000f
	)
);

TEMPER_PARAMETRIC( Test_double4x2_int4x4, TEMPER_FLAG_SHOULD_RUN, const int4x4& convertFrom, const double4x2& expectedAnswer )
{
	double4x2 actualAnswer = double4x2( convertFrom );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[0][0], actualAnswer[0][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[0][1], actualAnswer[0][1] ) );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[1][0], actualAnswer[1][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[1][1], actualAnswer[1][1] ) );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[2][0], actualAnswer[2][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[2][1], actualAnswer[2][1] ) );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[3][0], actualAnswer[3][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[3][1], actualAnswer[3][1] ) );

}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_int4x4,
	int4x4(
		0, 0, 0, 0,
		0, 0, 0, 0,
		0, 0, 0, 0,
		0, 0, 0, 0
	),
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_int4x4,
	int4x4(
		10, 10, 10, 10,
		10, 10, 10, 10,
		10, 10, 10, 10,
		10, 10, 10, 10
	),
	double4x2(
		10.000000f, 10.000000f,
		10.000000f, 10.000000f,
		10.000000f, 10.000000f,
		10.000000f, 10.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_int4x4,
	int4x4(
		10, 20, 30, 40,
		50, 60, 70, 80,
		90, 100, 110, 120,
		130, 140, 150, 160
	),
	double4x2(
		10.000000f, 20.000000f,
		50.000000f, 60.000000f,
		90.000000f, 100.000000f,
		130.000000f, 140.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_int4x4,
	int4x4(
		160, 150, 140, 130,
		120, 110, 100, 90,
		80, 70, 60, 50,
		40, 30, 20, 10
	),
	double4x2(
		160.000000f, 150.000000f,
		120.000000f, 110.000000f,
		80.000000f, 70.000000f,
		40.000000f, 30.000000f
	)
);

TEMPER_PARAMETRIC( Test_double4x2_uint4x2, TEMPER_FLAG_SHOULD_RUN, const uint4x2& convertFrom, const double4x2& expectedAnswer )
{
	double4x2 actualAnswer = double4x2( convertFrom );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[0][0], actualAnswer[0][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[0][1], actualAnswer[0][1] ) );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[1][0], actualAnswer[1][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[1][1], actualAnswer[1][1] ) );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[2][0], actualAnswer[2][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[2][1], actualAnswer[2][1] ) );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[3][0], actualAnswer[3][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[3][1], actualAnswer[3][1] ) );

}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_uint4x2,
	uint4x2(
		0U, 0U,
		0U, 0U,
		0U, 0U,
		0U, 0U
	),
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_uint4x2,
	uint4x2(
		10U, 10U,
		10U, 10U,
		10U, 10U,
		10U, 10U
	),
	double4x2(
		10.000000f, 10.000000f,
		10.000000f, 10.000000f,
		10.000000f, 10.000000f,
		10.000000f, 10.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_uint4x2,
	uint4x2(
		10U, 20U,
		50U, 60U,
		90U, 100U,
		130U, 140U
	),
	double4x2(
		10.000000f, 20.000000f,
		50.000000f, 60.000000f,
		90.000000f, 100.000000f,
		130.000000f, 140.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_uint4x2,
	uint4x2(
		160U, 150U,
		120U, 110U,
		80U, 70U,
		40U, 30U
	),
	double4x2(
		160.000000f, 150.000000f,
		120.000000f, 110.000000f,
		80.000000f, 70.000000f,
		40.000000f, 30.000000f
	)
);

TEMPER_PARAMETRIC( Test_double4x2_uint4x3, TEMPER_FLAG_SHOULD_RUN, const uint4x3& convertFrom, const double4x2& expectedAnswer )
{
	double4x2 actualAnswer = double4x2( convertFrom );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[0][0], actualAnswer[0][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[0][1], actualAnswer[0][1] ) );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[1][0], actualAnswer[1][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[1][1], actualAnswer[1][1] ) );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[2][0], actualAnswer[2][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[2][1], actualAnswer[2][1] ) );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[3][0], actualAnswer[3][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[3][1], actualAnswer[3][1] ) );

}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_uint4x3,
	uint4x3(
		0U, 0U, 0U,
		0U, 0U, 0U,
		0U, 0U, 0U,
		0U, 0U, 0U
	),
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_uint4x3,
	uint4x3(
		10U, 10U, 10U,
		10U, 10U, 10U,
		10U, 10U, 10U,
		10U, 10U, 10U
	),
	double4x2(
		10.000000f, 10.000000f,
		10.000000f, 10.000000f,
		10.000000f, 10.000000f,
		10.000000f, 10.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_uint4x3,
	uint4x3(
		10U, 20U, 30U,
		50U, 60U, 70U,
		90U, 100U, 110U,
		130U, 140U, 150U
	),
	double4x2(
		10.000000f, 20.000000f,
		50.000000f, 60.000000f,
		90.000000f, 100.000000f,
		130.000000f, 140.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_uint4x3,
	uint4x3(
		160U, 150U, 140U,
		120U, 110U, 100U,
		80U, 70U, 60U,
		40U, 30U, 20U
	),
	double4x2(
		160.000000f, 150.000000f,
		120.000000f, 110.000000f,
		80.000000f, 70.000000f,
		40.000000f, 30.000000f
	)
);

TEMPER_PARAMETRIC( Test_double4x2_uint4x4, TEMPER_FLAG_SHOULD_RUN, const uint4x4& convertFrom, const double4x2& expectedAnswer )
{
	double4x2 actualAnswer = double4x2( convertFrom );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[0][0], actualAnswer[0][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[0][1], actualAnswer[0][1] ) );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[1][0], actualAnswer[1][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[1][1], actualAnswer[1][1] ) );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[2][0], actualAnswer[2][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[2][1], actualAnswer[2][1] ) );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[3][0], actualAnswer[3][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[3][1], actualAnswer[3][1] ) );

}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_uint4x4,
	uint4x4(
		0U, 0U, 0U, 0U,
		0U, 0U, 0U, 0U,
		0U, 0U, 0U, 0U,
		0U, 0U, 0U, 0U
	),
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_uint4x4,
	uint4x4(
		10U, 10U, 10U, 10U,
		10U, 10U, 10U, 10U,
		10U, 10U, 10U, 10U,
		10U, 10U, 10U, 10U
	),
	double4x2(
		10.000000f, 10.000000f,
		10.000000f, 10.000000f,
		10.000000f, 10.000000f,
		10.000000f, 10.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_uint4x4,
	uint4x4(
		10U, 20U, 30U, 40U,
		50U, 60U, 70U, 80U,
		90U, 100U, 110U, 120U,
		130U, 140U, 150U, 160U
	),
	double4x2(
		10.000000f, 20.000000f,
		50.000000f, 60.000000f,
		90.000000f, 100.000000f,
		130.000000f, 140.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_uint4x4,
	uint4x4(
		160U, 150U, 140U, 130U,
		120U, 110U, 100U, 90U,
		80U, 70U, 60U, 50U,
		40U, 30U, 20U, 10U
	),
	double4x2(
		160.000000f, 150.000000f,
		120.000000f, 110.000000f,
		80.000000f, 70.000000f,
		40.000000f, 30.000000f
	)
);

TEMPER_PARAMETRIC( Test_double4x2_float4x2, TEMPER_FLAG_SHOULD_RUN, const float4x2& convertFrom, const double4x2& expectedAnswer )
{
	double4x2 actualAnswer = double4x2( convertFrom );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[0][0], actualAnswer[0][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[0][1], actualAnswer[0][1] ) );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[1][0], actualAnswer[1][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[1][1], actualAnswer[1][1] ) );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[2][0], actualAnswer[2][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[2][1], actualAnswer[2][1] ) );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[3][0], actualAnswer[3][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[3][1], actualAnswer[3][1] ) );

}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_float4x2,
	float4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	),
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_float4x2,
	float4x2(
		10.000000f, 10.000000f,
		10.000000f, 10.000000f,
		10.000000f, 10.000000f,
		10.000000f, 10.000000f
	),
	double4x2(
		10.000000f, 10.000000f,
		10.000000f, 10.000000f,
		10.000000f, 10.000000f,
		10.000000f, 10.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_float4x2,
	float4x2(
		10.000000f, 20.000000f,
		50.000000f, 60.000000f,
		90.000000f, 100.000000f,
		130.000000f, 140.000000f
	),
	double4x2(
		10.000000f, 20.000000f,
		50.000000f, 60.000000f,
		90.000000f, 100.000000f,
		130.000000f, 140.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_float4x2,
	float4x2(
		160.000000f, 150.000000f,
		120.000000f, 110.000000f,
		80.000000f, 70.000000f,
		40.000000f, 30.000000f
	),
	double4x2(
		160.000000f, 150.000000f,
		120.000000f, 110.000000f,
		80.000000f, 70.000000f,
		40.000000f, 30.000000f
	)
);

TEMPER_PARAMETRIC( Test_double4x2_float4x3, TEMPER_FLAG_SHOULD_RUN, const float4x3& convertFrom, const double4x2& expectedAnswer )
{
	double4x2 actualAnswer = double4x2( convertFrom );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[0][0], actualAnswer[0][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[0][1], actualAnswer[0][1] ) );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[1][0], actualAnswer[1][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[1][1], actualAnswer[1][1] ) );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[2][0], actualAnswer[2][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[2][1], actualAnswer[2][1] ) );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[3][0], actualAnswer[3][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[3][1], actualAnswer[3][1] ) );

}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_float4x3,
	float4x3(
		0.000000f, 0.000000f, 0.000000f,
		0.000000f, 0.000000f, 0.000000f,
		0.000000f, 0.000000f, 0.000000f,
		0.000000f, 0.000000f, 0.000000f
	),
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_float4x3,
	float4x3(
		10.000000f, 10.000000f, 10.000000f,
		10.000000f, 10.000000f, 10.000000f,
		10.000000f, 10.000000f, 10.000000f,
		10.000000f, 10.000000f, 10.000000f
	),
	double4x2(
		10.000000f, 10.000000f,
		10.000000f, 10.000000f,
		10.000000f, 10.000000f,
		10.000000f, 10.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_float4x3,
	float4x3(
		10.000000f, 20.000000f, 30.000000f,
		50.000000f, 60.000000f, 70.000000f,
		90.000000f, 100.000000f, 110.000000f,
		130.000000f, 140.000000f, 150.000000f
	),
	double4x2(
		10.000000f, 20.000000f,
		50.000000f, 60.000000f,
		90.000000f, 100.000000f,
		130.000000f, 140.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_float4x3,
	float4x3(
		160.000000f, 150.000000f, 140.000000f,
		120.000000f, 110.000000f, 100.000000f,
		80.000000f, 70.000000f, 60.000000f,
		40.000000f, 30.000000f, 20.000000f
	),
	double4x2(
		160.000000f, 150.000000f,
		120.000000f, 110.000000f,
		80.000000f, 70.000000f,
		40.000000f, 30.000000f
	)
);

TEMPER_PARAMETRIC( Test_double4x2_float4x4, TEMPER_FLAG_SHOULD_RUN, const float4x4& convertFrom, const double4x2& expectedAnswer )
{
	double4x2 actualAnswer = double4x2( convertFrom );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[0][0], actualAnswer[0][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[0][1], actualAnswer[0][1] ) );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[1][0], actualAnswer[1][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[1][1], actualAnswer[1][1] ) );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[2][0], actualAnswer[2][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[2][1], actualAnswer[2][1] ) );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[3][0], actualAnswer[3][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[3][1], actualAnswer[3][1] ) );

}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_float4x4,
	float4x4(
		0.000000f, 0.000000f, 0.000000f, 0.000000f,
		0.000000f, 0.000000f, 0.000000f, 0.000000f,
		0.000000f, 0.000000f, 0.000000f, 0.000000f,
		0.000000f, 0.000000f, 0.000000f, 0.000000f
	),
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_float4x4,
	float4x4(
		10.000000f, 10.000000f, 10.000000f, 10.000000f,
		10.000000f, 10.000000f, 10.000000f, 10.000000f,
		10.000000f, 10.000000f, 10.000000f, 10.000000f,
		10.000000f, 10.000000f, 10.000000f, 10.000000f
	),
	double4x2(
		10.000000f, 10.000000f,
		10.000000f, 10.000000f,
		10.000000f, 10.000000f,
		10.000000f, 10.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_float4x4,
	float4x4(
		10.000000f, 20.000000f, 30.000000f, 40.000000f,
		50.000000f, 60.000000f, 70.000000f, 80.000000f,
		90.000000f, 100.000000f, 110.000000f, 120.000000f,
		130.000000f, 140.000000f, 150.000000f, 160.000000f
	),
	double4x2(
		10.000000f, 20.000000f,
		50.000000f, 60.000000f,
		90.000000f, 100.000000f,
		130.000000f, 140.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_float4x4,
	float4x4(
		160.000000f, 150.000000f, 140.000000f, 130.000000f,
		120.000000f, 110.000000f, 100.000000f, 90.000000f,
		80.000000f, 70.000000f, 60.000000f, 50.000000f,
		40.000000f, 30.000000f, 20.000000f, 10.000000f
	),
	double4x2(
		160.000000f, 150.000000f,
		120.000000f, 110.000000f,
		80.000000f, 70.000000f,
		40.000000f, 30.000000f
	)
);

TEMPER_PARAMETRIC( Test_double4x2_double4x2, TEMPER_FLAG_SHOULD_RUN, const double4x2& convertFrom, const double4x2& expectedAnswer )
{
	double4x2 actualAnswer = double4x2( convertFrom );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[0][0], actualAnswer[0][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[0][1], actualAnswer[0][1] ) );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[1][0], actualAnswer[1][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[1][1], actualAnswer[1][1] ) );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[2][0], actualAnswer[2][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[2][1], actualAnswer[2][1] ) );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[3][0], actualAnswer[3][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[3][1], actualAnswer[3][1] ) );

}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_double4x2,
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	),
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_double4x2,
	double4x2(
		10.000000f, 10.000000f,
		10.000000f, 10.000000f,
		10.000000f, 10.000000f,
		10.000000f, 10.000000f
	),
	double4x2(
		10.000000f, 10.000000f,
		10.000000f, 10.000000f,
		10.000000f, 10.000000f,
		10.000000f, 10.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_double4x2,
	double4x2(
		10.000000f, 20.000000f,
		50.000000f, 60.000000f,
		90.000000f, 100.000000f,
		130.000000f, 140.000000f
	),
	double4x2(
		10.000000f, 20.000000f,
		50.000000f, 60.000000f,
		90.000000f, 100.000000f,
		130.000000f, 140.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_double4x2,
	double4x2(
		160.000000f, 150.000000f,
		120.000000f, 110.000000f,
		80.000000f, 70.000000f,
		40.000000f, 30.000000f
	),
	double4x2(
		160.000000f, 150.000000f,
		120.000000f, 110.000000f,
		80.000000f, 70.000000f,
		40.000000f, 30.000000f
	)
);

TEMPER_PARAMETRIC( Test_double4x2_double4x3, TEMPER_FLAG_SHOULD_RUN, const double4x3& convertFrom, const double4x2& expectedAnswer )
{
	double4x2 actualAnswer = double4x2( convertFrom );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[0][0], actualAnswer[0][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[0][1], actualAnswer[0][1] ) );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[1][0], actualAnswer[1][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[1][1], actualAnswer[1][1] ) );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[2][0], actualAnswer[2][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[2][1], actualAnswer[2][1] ) );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[3][0], actualAnswer[3][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[3][1], actualAnswer[3][1] ) );

}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_double4x3,
	double4x3(
		0.000000f, 0.000000f, 0.000000f,
		0.000000f, 0.000000f, 0.000000f,
		0.000000f, 0.000000f, 0.000000f,
		0.000000f, 0.000000f, 0.000000f
	),
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_double4x3,
	double4x3(
		10.000000f, 10.000000f, 10.000000f,
		10.000000f, 10.000000f, 10.000000f,
		10.000000f, 10.000000f, 10.000000f,
		10.000000f, 10.000000f, 10.000000f
	),
	double4x2(
		10.000000f, 10.000000f,
		10.000000f, 10.000000f,
		10.000000f, 10.000000f,
		10.000000f, 10.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_double4x3,
	double4x3(
		10.000000f, 20.000000f, 30.000000f,
		50.000000f, 60.000000f, 70.000000f,
		90.000000f, 100.000000f, 110.000000f,
		130.000000f, 140.000000f, 150.000000f
	),
	double4x2(
		10.000000f, 20.000000f,
		50.000000f, 60.000000f,
		90.000000f, 100.000000f,
		130.000000f, 140.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_double4x3,
	double4x3(
		160.000000f, 150.000000f, 140.000000f,
		120.000000f, 110.000000f, 100.000000f,
		80.000000f, 70.000000f, 60.000000f,
		40.000000f, 30.000000f, 20.000000f
	),
	double4x2(
		160.000000f, 150.000000f,
		120.000000f, 110.000000f,
		80.000000f, 70.000000f,
		40.000000f, 30.000000f
	)
);

TEMPER_PARAMETRIC( Test_double4x2_double4x4, TEMPER_FLAG_SHOULD_RUN, const double4x4& convertFrom, const double4x2& expectedAnswer )
{
	double4x2 actualAnswer = double4x2( convertFrom );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[0][0], actualAnswer[0][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[0][1], actualAnswer[0][1] ) );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[1][0], actualAnswer[1][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[1][1], actualAnswer[1][1] ) );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[2][0], actualAnswer[2][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[2][1], actualAnswer[2][1] ) );

	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[3][0], actualAnswer[3][0] ) );
	TEMPER_CHECK_TRUE( doubleeq( expectedAnswer[3][1], actualAnswer[3][1] ) );

}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_double4x4,
	double4x4(
		0.000000f, 0.000000f, 0.000000f, 0.000000f,
		0.000000f, 0.000000f, 0.000000f, 0.000000f,
		0.000000f, 0.000000f, 0.000000f, 0.000000f,
		0.000000f, 0.000000f, 0.000000f, 0.000000f
	),
	double4x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_double4x4,
	double4x4(
		10.000000f, 10.000000f, 10.000000f, 10.000000f,
		10.000000f, 10.000000f, 10.000000f, 10.000000f,
		10.000000f, 10.000000f, 10.000000f, 10.000000f,
		10.000000f, 10.000000f, 10.000000f, 10.000000f
	),
	double4x2(
		10.000000f, 10.000000f,
		10.000000f, 10.000000f,
		10.000000f, 10.000000f,
		10.000000f, 10.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_double4x4,
	double4x4(
		10.000000f, 20.000000f, 30.000000f, 40.000000f,
		50.000000f, 60.000000f, 70.000000f, 80.000000f,
		90.000000f, 100.000000f, 110.000000f, 120.000000f,
		130.000000f, 140.000000f, 150.000000f, 160.000000f
	),
	double4x2(
		10.000000f, 20.000000f,
		50.000000f, 60.000000f,
		90.000000f, 100.000000f,
		130.000000f, 140.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_double4x4,
	double4x4(
		160.000000f, 150.000000f, 140.000000f, 130.000000f,
		120.000000f, 110.000000f, 100.000000f, 90.000000f,
		80.000000f, 70.000000f, 60.000000f, 50.000000f,
		40.000000f, 30.000000f, 20.000000f, 10.000000f
	),
	double4x2(
		160.000000f, 150.000000f,
		120.000000f, 110.000000f,
		80.000000f, 70.000000f,
		40.000000f, 30.000000f
	)
);

TEMPER_PARAMETRIC( Test_double4x2_identity, TEMPER_FLAG_SHOULD_RUN, const double4x2& matrix, const bool expectedAnswer )
{
	double4x2 identityMat;
	identity( identityMat );
	bool isMatrixIdentity = ( identityMat == matrix );
	TEMPER_CHECK_TRUE( isMatrixIdentity == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_identity,
	double4x2(
		1.000000f, 0.000000f,
		0.000000f, 1.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	),
	true
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_identity,
	double4x2(
		1.000000f, 1.000000f,
		0.000000f, 1.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	),
	false
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_identity,
	double4x2(
		1.000000f, 0.000000f,
		1.000000f, 1.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	),
	false
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_identity,
	double4x2(
		1.000000f, 1.000000f,
		1.000000f, 1.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	),
	false
);

TEMPER_PARAMETRIC( Test_double4x2_transpose, TEMPER_FLAG_SHOULD_RUN, const double4x2& matrix, const double2x4& expectedAnswer )
{
	double2x4 actualResult = transpose( matrix );
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_transpose,
	double4x2(
		1.000000f, 0.000000f,
		0.000000f, 1.000000f,
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	),
	double2x4(
		1.000000f, 0.000000f, 0.000000f, 0.000000f,
		0.000000f, 1.000000f, 0.000000f, 0.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_transpose,
	double4x2(
		0.000000f, 1.000000f,
		4.000000f, 5.000000f,
		8.000000f, 9.000000f,
		12.000000f, 13.000000f
	),
	double2x4(
		0.000000f, 4.000000f, 8.000000f, 12.000000f,
		1.000000f, 5.000000f, 9.000000f, 13.000000f
	)
);

TEMPER_PARAMETRIC( Test_double4x2_mulm, TEMPER_FLAG_SHOULD_RUN, const double4x2& lhs, const double2x4& rhs, const double4x4& expectedAnswer )
{
	double4x4 actualResult = mul( lhs, rhs );
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_mulm,
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	),
	double2x4(
		4.000000f, 4.000000f, 4.000000f, 4.000000f,
		4.000000f, 4.000000f, 4.000000f, 4.000000f
	),
	double4x4(
		16.000000f, 16.000000f, 16.000000f, 16.000000f,
		16.000000f, 16.000000f, 16.000000f, 16.000000f,
		16.000000f, 16.000000f, 16.000000f, 16.000000f,
		16.000000f, 16.000000f, 16.000000f, 16.000000f
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_double4x2_mulm,
	double4x2(
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f,
		2.000000f, 2.000000f
	),
	double2x4(
		1.000000f, 0.000000f, 0.000000f, 0.000000f,
		0.000000f, 1.000000f, 0.000000f, 0.000000f
	),
	double4x4(
		2.000000f, 2.000000f, 0.000000f, 0.000000f,
		2.000000f, 2.000000f, 0.000000f, 0.000000f,
		2.000000f, 2.000000f, 0.000000f, 0.000000f,
		2.000000f, 2.000000f, 0.000000f, 0.000000f
	)
);

