/*
===========================================================================

HLML.

MIT License

Copyright (c) 2019 Dan Moody

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

===========================================================================
*/

// THIS FILE WAS AUTOMATICALLY GENERATED BY A TOOL.
// EDITING THIS FILE MAY CAUSE SIDE EFFECTS.
// DO SO AT YOUR OWN RISK.

TEMPER_PARAMETRIC( Test_int2x3_less_than, TEMPER_FLAG_SHOULD_RUN, const int2x3& lhs, const int2x3& rhs, const bool2x3& expectedAnswer )
{
	bool2x3 actualResult = lhs < rhs;
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_less_than,
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	bool2x3(
		false, false, false,
		false, false, false
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_less_than,
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	bool2x3(
		true, true, true,
		true, true, true
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_less_than,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	bool2x3(
		false, false, false,
		false, false, false
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_less_than,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	bool2x3(
		false, false, false,
		false, false, false
	)
);

TEMPER_PARAMETRIC( Test_int2x3_less_than_equal, TEMPER_FLAG_SHOULD_RUN, const int2x3& lhs, const int2x3& rhs, const bool2x3& expectedAnswer )
{
	bool2x3 actualResult = lhs <= rhs;
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_less_than_equal,
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	bool2x3(
		true, true, true,
		true, true, true
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_less_than_equal,
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	bool2x3(
		true, true, true,
		true, true, true
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_less_than_equal,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	bool2x3(
		true, true, true,
		true, true, true
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_less_than_equal,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	bool2x3(
		false, false, false,
		false, false, false
	)
);

TEMPER_PARAMETRIC( Test_int2x3_greater_than, TEMPER_FLAG_SHOULD_RUN, const int2x3& lhs, const int2x3& rhs, const bool2x3& expectedAnswer )
{
	bool2x3 actualResult = lhs > rhs;
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_greater_than,
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	bool2x3(
		false, false, false,
		false, false, false
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_greater_than,
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	bool2x3(
		false, false, false,
		false, false, false
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_greater_than,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	bool2x3(
		false, false, false,
		false, false, false
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_greater_than,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	bool2x3(
		true, true, true,
		true, true, true
	)
);

TEMPER_PARAMETRIC( Test_int2x3_greater_than_equal, TEMPER_FLAG_SHOULD_RUN, const int2x3& lhs, const int2x3& rhs, const bool2x3& expectedAnswer )
{
	bool2x3 actualResult = lhs >= rhs;
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_greater_than_equal,
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	bool2x3(
		true, true, true,
		true, true, true
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_greater_than_equal,
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	bool2x3(
		false, false, false,
		false, false, false
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_greater_than_equal,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	bool2x3(
		true, true, true,
		true, true, true
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_greater_than_equal,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	bool2x3(
		true, true, true,
		true, true, true
	)
);

TEMPER_PARAMETRIC( Test_int2x3_cadds, TEMPER_FLAG_SHOULD_RUN, const int2x3& lhs, const int32_t& rhs, const int2x3& expectedAnswer )
{
	int2x3 actualResult = lhs + rhs;
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cadds,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	1,
	int2x3(
		2, 2, 2,
		2, 2, 2
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cadds,
	int2x3(
		2, 2, 2,
		2, 2, 2
	),
	2,
	int2x3(
		4, 4, 4,
		4, 4, 4
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cadds,
	int2x3(
		4, 4, 4,
		4, 4, 4
	),
	2,
	int2x3(
		6, 6, 6,
		6, 6, 6
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cadds,
	int2x3(
		8, 8, 8,
		8, 8, 8
	),
	4,
	int2x3(
		12, 12, 12,
		12, 12, 12
	)
);

TEMPER_PARAMETRIC( Test_int2x3_csubs, TEMPER_FLAG_SHOULD_RUN, const int2x3& lhs, const int32_t& rhs, const int2x3& expectedAnswer )
{
	int2x3 actualResult = lhs - rhs;
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_csubs,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	1,
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_csubs,
	int2x3(
		2, 2, 2,
		2, 2, 2
	),
	2,
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_csubs,
	int2x3(
		4, 4, 4,
		4, 4, 4
	),
	2,
	int2x3(
		2, 2, 2,
		2, 2, 2
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_csubs,
	int2x3(
		8, 8, 8,
		8, 8, 8
	),
	4,
	int2x3(
		4, 4, 4,
		4, 4, 4
	)
);

TEMPER_PARAMETRIC( Test_int2x3_cmuls, TEMPER_FLAG_SHOULD_RUN, const int2x3& lhs, const int32_t& rhs, const int2x3& expectedAnswer )
{
	int2x3 actualResult = lhs * rhs;
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cmuls,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	1,
	int2x3(
		1, 1, 1,
		1, 1, 1
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cmuls,
	int2x3(
		2, 2, 2,
		2, 2, 2
	),
	2,
	int2x3(
		4, 4, 4,
		4, 4, 4
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cmuls,
	int2x3(
		4, 4, 4,
		4, 4, 4
	),
	2,
	int2x3(
		8, 8, 8,
		8, 8, 8
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cmuls,
	int2x3(
		8, 8, 8,
		8, 8, 8
	),
	4,
	int2x3(
		32, 32, 32,
		32, 32, 32
	)
);

TEMPER_PARAMETRIC( Test_int2x3_cdivs, TEMPER_FLAG_SHOULD_RUN, const int2x3& lhs, const int32_t& rhs, const int2x3& expectedAnswer )
{
	int2x3 actualResult = lhs / rhs;
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cdivs,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	1,
	int2x3(
		1, 1, 1,
		1, 1, 1
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cdivs,
	int2x3(
		2, 2, 2,
		2, 2, 2
	),
	2,
	int2x3(
		1, 1, 1,
		1, 1, 1
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cdivs,
	int2x3(
		4, 4, 4,
		4, 4, 4
	),
	2,
	int2x3(
		2, 2, 2,
		2, 2, 2
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cdivs,
	int2x3(
		8, 8, 8,
		8, 8, 8
	),
	4,
	int2x3(
		2, 2, 2,
		2, 2, 2
	)
);

TEMPER_PARAMETRIC( Test_int2x3_caddm, TEMPER_FLAG_SHOULD_RUN, const int2x3& lhs, const int2x3& rhs, const int2x3& expectedAnswer )
{
	int2x3 actualResult = lhs + rhs;
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_caddm,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		2, 2, 2,
		2, 2, 2
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_caddm,
	int2x3(
		2, 2, 2,
		2, 2, 2
	),
	int2x3(
		2, 2, 2,
		2, 2, 2
	),
	int2x3(
		4, 4, 4,
		4, 4, 4
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_caddm,
	int2x3(
		4, 4, 4,
		4, 4, 4
	),
	int2x3(
		2, 2, 2,
		2, 2, 2
	),
	int2x3(
		6, 6, 6,
		6, 6, 6
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_caddm,
	int2x3(
		8, 8, 8,
		8, 8, 8
	),
	int2x3(
		4, 4, 4,
		4, 4, 4
	),
	int2x3(
		12, 12, 12,
		12, 12, 12
	)
);

TEMPER_PARAMETRIC( Test_int2x3_csubm, TEMPER_FLAG_SHOULD_RUN, const int2x3& lhs, const int2x3& rhs, const int2x3& expectedAnswer )
{
	int2x3 actualResult = lhs - rhs;
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_csubm,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_csubm,
	int2x3(
		2, 2, 2,
		2, 2, 2
	),
	int2x3(
		2, 2, 2,
		2, 2, 2
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_csubm,
	int2x3(
		4, 4, 4,
		4, 4, 4
	),
	int2x3(
		2, 2, 2,
		2, 2, 2
	),
	int2x3(
		2, 2, 2,
		2, 2, 2
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_csubm,
	int2x3(
		8, 8, 8,
		8, 8, 8
	),
	int2x3(
		4, 4, 4,
		4, 4, 4
	),
	int2x3(
		4, 4, 4,
		4, 4, 4
	)
);

TEMPER_PARAMETRIC( Test_int2x3_cmulm, TEMPER_FLAG_SHOULD_RUN, const int2x3& lhs, const int2x3& rhs, const int2x3& expectedAnswer )
{
	int2x3 actualResult = lhs * rhs;
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cmulm,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cmulm,
	int2x3(
		2, 2, 2,
		2, 2, 2
	),
	int2x3(
		2, 2, 2,
		2, 2, 2
	),
	int2x3(
		4, 4, 4,
		4, 4, 4
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cmulm,
	int2x3(
		4, 4, 4,
		4, 4, 4
	),
	int2x3(
		2, 2, 2,
		2, 2, 2
	),
	int2x3(
		8, 8, 8,
		8, 8, 8
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cmulm,
	int2x3(
		8, 8, 8,
		8, 8, 8
	),
	int2x3(
		4, 4, 4,
		4, 4, 4
	),
	int2x3(
		32, 32, 32,
		32, 32, 32
	)
);

TEMPER_PARAMETRIC( Test_int2x3_cdivm, TEMPER_FLAG_SHOULD_RUN, const int2x3& lhs, const int2x3& rhs, const int2x3& expectedAnswer )
{
	int2x3 actualResult = lhs / rhs;
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cdivm,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cdivm,
	int2x3(
		2, 2, 2,
		2, 2, 2
	),
	int2x3(
		2, 2, 2,
		2, 2, 2
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cdivm,
	int2x3(
		4, 4, 4,
		4, 4, 4
	),
	int2x3(
		2, 2, 2,
		2, 2, 2
	),
	int2x3(
		2, 2, 2,
		2, 2, 2
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cdivm,
	int2x3(
		8, 8, 8,
		8, 8, 8
	),
	int2x3(
		4, 4, 4,
		4, 4, 4
	),
	int2x3(
		2, 2, 2,
		2, 2, 2
	)
);

#if defined( __GNUC__ ) || defined( __clang__ )
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wcast-qual"
#endif

TEMPER_PARAMETRIC( Test_int2x3_increment_prefix, TEMPER_FLAG_SHOULD_RUN, const int2x3& x, const int2x3& expectedAnswer )
{
	// make local copy of x and use that because we cant do increment or decrement operations on a const reference
	// and MSVC throws warnings if we just make the parameter a non-const reference
	int2x3 xlocal = (int2x3) x;
	int2x3 actualAnswer = ++xlocal;
	TEMPER_CHECK_TRUE( actualAnswer == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_increment_prefix,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		2, 2, 2,
		2, 2, 2
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_increment_prefix,
	int2x3(
		2, 2, 2,
		2, 2, 2
	),
	int2x3(
		3, 3, 3,
		3, 3, 3
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_increment_prefix,
	int2x3(
		3, 3, 3,
		3, 3, 3
	),
	int2x3(
		4, 4, 4,
		4, 4, 4
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_increment_prefix,
	int2x3(
		4, 4, 4,
		4, 4, 4
	),
	int2x3(
		5, 5, 5,
		5, 5, 5
	)
);

TEMPER_PARAMETRIC( Test_int2x3_increment_postfix, TEMPER_FLAG_SHOULD_RUN, const int2x3& x, const int2x3& expectedAnswer )
{
	// make local copy of x and use that because we cant do increment or decrement operations on a const reference
	// and MSVC throws warnings if we just make the parameter a non-const reference
	int2x3 xlocal = (int2x3) x;
	int2x3 actualAnswer = xlocal++;
	TEMPER_CHECK_TRUE( actualAnswer == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_increment_postfix,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		2, 2, 2,
		2, 2, 2
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_increment_postfix,
	int2x3(
		2, 2, 2,
		2, 2, 2
	),
	int2x3(
		3, 3, 3,
		3, 3, 3
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_increment_postfix,
	int2x3(
		3, 3, 3,
		3, 3, 3
	),
	int2x3(
		4, 4, 4,
		4, 4, 4
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_increment_postfix,
	int2x3(
		4, 4, 4,
		4, 4, 4
	),
	int2x3(
		5, 5, 5,
		5, 5, 5
	)
);

TEMPER_PARAMETRIC( Test_int2x3_decrement_prefix, TEMPER_FLAG_SHOULD_RUN, const int2x3& x, const int2x3& expectedAnswer )
{
	// make local copy of x and use that because we cant do increment or decrement operations on a const reference
	// and MSVC throws warnings if we just make the parameter a non-const reference
	int2x3 xlocal = (int2x3) x;
	int2x3 actualAnswer = --xlocal;
	TEMPER_CHECK_TRUE( actualAnswer == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_decrement_prefix,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_decrement_prefix,
	int2x3(
		2, 2, 2,
		2, 2, 2
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_decrement_prefix,
	int2x3(
		3, 3, 3,
		3, 3, 3
	),
	int2x3(
		2, 2, 2,
		2, 2, 2
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_decrement_prefix,
	int2x3(
		4, 4, 4,
		4, 4, 4
	),
	int2x3(
		3, 3, 3,
		3, 3, 3
	)
);

TEMPER_PARAMETRIC( Test_int2x3_decrement_postfix, TEMPER_FLAG_SHOULD_RUN, const int2x3& x, const int2x3& expectedAnswer )
{
	// make local copy of x and use that because we cant do increment or decrement operations on a const reference
	// and MSVC throws warnings if we just make the parameter a non-const reference
	int2x3 xlocal = (int2x3) x;
	int2x3 actualAnswer = xlocal--;
	TEMPER_CHECK_TRUE( actualAnswer == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_decrement_postfix,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_decrement_postfix,
	int2x3(
		2, 2, 2,
		2, 2, 2
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_decrement_postfix,
	int2x3(
		3, 3, 3,
		3, 3, 3
	),
	int2x3(
		2, 2, 2,
		2, 2, 2
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_decrement_postfix,
	int2x3(
		4, 4, 4,
		4, 4, 4
	),
	int2x3(
		3, 3, 3,
		3, 3, 3
	)
);

#if defined( __GNUC__ ) || defined( __clang__ )
#pragma GCC diagnostic pop
#endif
#if defined( __GNUC__ ) || defined( __clang__ )
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wcast-qual"
#endif
TEMPER_PARAMETRIC( Test_int2x3_negate_prefix, TEMPER_FLAG_SHOULD_RUN, const int2x3& x, const int2x3& expectedAnswer )
{
	// make local copy of x and use that because we cant do increment or decrement operations on a const reference
	// and MSVC throws warnings if we just make the parameter a non-const reference
	int2x3 xlocal = (int2x3) x;
	int2x3 actualAnswer = -xlocal;
	TEMPER_CHECK_TRUE( actualAnswer == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_negate_prefix,
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_negate_prefix,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		-1, -1, -1,
		-1, -1, -1
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_negate_prefix,
	int2x3(
		2, 2, 2,
		2, 2, 2
	),
	int2x3(
		-2, -2, -2,
		-2, -2, -2
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_negate_prefix,
	int2x3(
		3, 3, 3,
		3, 3, 3
	),
	int2x3(
		-3, -3, -3,
		-3, -3, -3
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_negate_prefix,
	int2x3(
		10, 10, 10,
		10, 10, 10
	),
	int2x3(
		-10, -10, -10,
		-10, -10, -10
	)
);

#if defined( __GNUC__ ) || defined( __clang__ )
#pragma GCC diagnostic pop
#endif

#if defined( __GNUC__ ) || defined( __clang__ )
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wcast-qual"
#endif
TEMPER_PARAMETRIC( Test_int2x3_not_prefix, TEMPER_FLAG_SHOULD_RUN, const int2x3& x, const int2x3& expectedAnswer )
{
	// make local copy of x and use that because we cant do increment or decrement operations on a const reference
	// and MSVC throws warnings if we just make the parameter a non-const reference
	int2x3 xlocal = (int2x3) x;
	int2x3 actualAnswer = ~xlocal;
	TEMPER_CHECK_TRUE( actualAnswer == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_not_prefix,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		-2, -2, -2,
		-2, -2, -2
	)
);

#if defined( __GNUC__ ) || defined( __clang__ )
#pragma GCC diagnostic pop
#endif

TEMPER_PARAMETRIC( Test_int2x3_cands, TEMPER_FLAG_SHOULD_RUN, const int2x3& lhs, const int32_t& rhs, const int2x3& expectedAnswer )
{
	int2x3 actualResult = lhs & rhs;
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cands,
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	0,
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cands,
	int2x3(
		2, 2, 2,
		2, 2, 2
	),
	1,
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cands,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	0,
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cands,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	1,
	int2x3(
		1, 1, 1,
		1, 1, 1
	)
);

TEMPER_PARAMETRIC( Test_int2x3_cors, TEMPER_FLAG_SHOULD_RUN, const int2x3& lhs, const int32_t& rhs, const int2x3& expectedAnswer )
{
	int2x3 actualResult = lhs | rhs;
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cors,
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	0,
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cors,
	int2x3(
		2, 2, 2,
		2, 2, 2
	),
	1,
	int2x3(
		3, 3, 3,
		3, 3, 3
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cors,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	0,
	int2x3(
		1, 1, 1,
		1, 1, 1
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cors,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	1,
	int2x3(
		1, 1, 1,
		1, 1, 1
	)
);

TEMPER_PARAMETRIC( Test_int2x3_cxors, TEMPER_FLAG_SHOULD_RUN, const int2x3& lhs, const int32_t& rhs, const int2x3& expectedAnswer )
{
	int2x3 actualResult = lhs ^ rhs;
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cxors,
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	0,
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cxors,
	int2x3(
		2, 2, 2,
		2, 2, 2
	),
	1,
	int2x3(
		3, 3, 3,
		3, 3, 3
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cxors,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	0,
	int2x3(
		1, 1, 1,
		1, 1, 1
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cxors,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	1,
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_PARAMETRIC( Test_int2x3_cshift_lefts, TEMPER_FLAG_SHOULD_RUN, const int2x3& lhs, const int32_t& rhs, const int2x3& expectedAnswer )
{
	int2x3 actualResult = lhs << rhs;
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cshift_lefts,
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	0,
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cshift_lefts,
	int2x3(
		2, 2, 2,
		2, 2, 2
	),
	1,
	int2x3(
		4, 4, 4,
		4, 4, 4
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cshift_lefts,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	0,
	int2x3(
		1, 1, 1,
		1, 1, 1
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cshift_lefts,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	1,
	int2x3(
		2, 2, 2,
		2, 2, 2
	)
);

TEMPER_PARAMETRIC( Test_int2x3_cshift_rights, TEMPER_FLAG_SHOULD_RUN, const int2x3& lhs, const int32_t& rhs, const int2x3& expectedAnswer )
{
	int2x3 actualResult = lhs >> rhs;
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cshift_rights,
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	0,
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cshift_rights,
	int2x3(
		2, 2, 2,
		2, 2, 2
	),
	1,
	int2x3(
		1, 1, 1,
		1, 1, 1
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cshift_rights,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	0,
	int2x3(
		1, 1, 1,
		1, 1, 1
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cshift_rights,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	1,
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_PARAMETRIC( Test_int2x3_candm, TEMPER_FLAG_SHOULD_RUN, const int2x3& lhs, const int2x3& rhs, const int2x3& expectedAnswer )
{
	int2x3 actualResult = lhs & rhs;
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_candm,
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_candm,
	int2x3(
		2, 2, 2,
		2, 2, 2
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_candm,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_candm,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	)
);

TEMPER_PARAMETRIC( Test_int2x3_corm, TEMPER_FLAG_SHOULD_RUN, const int2x3& lhs, const int2x3& rhs, const int2x3& expectedAnswer )
{
	int2x3 actualResult = lhs | rhs;
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_corm,
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_corm,
	int2x3(
		2, 2, 2,
		2, 2, 2
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		3, 3, 3,
		3, 3, 3
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_corm,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_corm,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	)
);

TEMPER_PARAMETRIC( Test_int2x3_cxorm, TEMPER_FLAG_SHOULD_RUN, const int2x3& lhs, const int2x3& rhs, const int2x3& expectedAnswer )
{
	int2x3 actualResult = lhs ^ rhs;
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cxorm,
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cxorm,
	int2x3(
		2, 2, 2,
		2, 2, 2
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		3, 3, 3,
		3, 3, 3
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cxorm,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cxorm,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_PARAMETRIC( Test_int2x3_cshift_leftm, TEMPER_FLAG_SHOULD_RUN, const int2x3& lhs, const int2x3& rhs, const int2x3& expectedAnswer )
{
	int2x3 actualResult = lhs << rhs;
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cshift_leftm,
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cshift_leftm,
	int2x3(
		2, 2, 2,
		2, 2, 2
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		4, 4, 4,
		4, 4, 4
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cshift_leftm,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cshift_leftm,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		2, 2, 2,
		2, 2, 2
	)
);

TEMPER_PARAMETRIC( Test_int2x3_cshift_rightm, TEMPER_FLAG_SHOULD_RUN, const int2x3& lhs, const int2x3& rhs, const int2x3& expectedAnswer )
{
	int2x3 actualResult = lhs >> rhs;
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cshift_rightm,
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cshift_rightm,
	int2x3(
		2, 2, 2,
		2, 2, 2
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cshift_rightm,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_cshift_rightm,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_PARAMETRIC( Test_int2x3_min, TEMPER_FLAG_SHOULD_RUN, const int2x3& lhs, const int2x3& rhs, const int2x3& expectedAnswer )
{
	int2x3 actualResult = min( lhs, rhs );
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_min,
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_min,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		2, 2, 2,
		2, 2, 2
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_min,
	int2x3(
		420, 420, 420,
		420, 420, 420
	),
	int2x3(
		69, 69, 69,
		69, 69, 69
	),
	int2x3(
		69, 69, 69,
		69, 69, 69
	)
);

TEMPER_PARAMETRIC( Test_int2x3_max, TEMPER_FLAG_SHOULD_RUN, const int2x3& lhs, const int2x3& rhs, const int2x3& expectedAnswer )
{
	int2x3 actualResult = max( lhs, rhs );
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_max,
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_max,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		2, 2, 2,
		2, 2, 2
	),
	int2x3(
		2, 2, 2,
		2, 2, 2
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_max,
	int2x3(
		69, 69, 69,
		69, 69, 69
	),
	int2x3(
		420, 420, 420,
		420, 420, 420
	),
	int2x3(
		420, 420, 420,
		420, 420, 420
	)
);

TEMPER_PARAMETRIC( Test_int2x3_saturate, TEMPER_FLAG_SHOULD_RUN, const int2x3& x, const int2x3& expectedAnswer )
{
	int2x3 actualResult = saturate( x );
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_saturate,
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_saturate,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_saturate,
	int2x3(
		2, 2, 2,
		2, 2, 2
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_saturate,
	int2x3(
		3, 3, 3,
		3, 3, 3
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_saturate,
	int2x3(
		10, 10, 10,
		10, 10, 10
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	)
);

TEMPER_PARAMETRIC( Test_int2x3_sign, TEMPER_FLAG_SHOULD_RUN, const int2x3& x, const int2x3& expectedAnswer )
{
	int2x3 actualResult = sign( x );
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_sign,
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_sign,
	int2x3(
		1, 1, 1,
		1, 1, 1
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_sign,
	int2x3(
		2, 2, 2,
		2, 2, 2
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_sign,
	int2x3(
		3, 3, 3,
		3, 3, 3
	),
	int2x3(
		1, 1, 1,
		1, 1, 1
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_sign,
	int2x3(
		-1, -1, -1,
		-1, -1, -1
	),
	int2x3(
		-1, -1, -1,
		-1, -1, -1
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_sign,
	int2x3(
		-2, -2, -2,
		-2, -2, -2
	),
	int2x3(
		-1, -1, -1,
		-1, -1, -1
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_sign,
	int2x3(
		-3, -3, -3,
		-3, -3, -3
	),
	int2x3(
		-1, -1, -1,
		-1, -1, -1
	)
);

TEMPER_PARAMETRIC( Test_int2x3_int2x2, TEMPER_FLAG_SHOULD_RUN, const int2x2& convertFrom, const int2x3& expectedAnswer )
{
	int2x3 actualAnswer = int2x3( convertFrom );

	TEMPER_CHECK_TRUE( expectedAnswer[0][0] == actualAnswer[0][0] );
	TEMPER_CHECK_TRUE( expectedAnswer[0][1] == actualAnswer[0][1] );

	TEMPER_CHECK_TRUE( expectedAnswer[1][0] == actualAnswer[1][0] );
	TEMPER_CHECK_TRUE( expectedAnswer[1][1] == actualAnswer[1][1] );

}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_int2x2,
	int2x2(
		0, 0,
		0, 0
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_int2x2,
	int2x2(
		10, 10,
		10, 10
	),
	int2x3(
		10, 10, 10,
		10, 10, 10
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_int2x2,
	int2x2(
		10, 20,
		50, 60
	),
	int2x3(
		10, 20, 30,
		50, 60, 70
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_int2x2,
	int2x2(
		160, 150,
		120, 110
	),
	int2x3(
		160, 150, 140,
		120, 110, 100
	)
);

TEMPER_PARAMETRIC( Test_int2x3_int2x3, TEMPER_FLAG_SHOULD_RUN, const int2x3& convertFrom, const int2x3& expectedAnswer )
{
	int2x3 actualAnswer = int2x3( convertFrom );

	TEMPER_CHECK_TRUE( expectedAnswer[0][0] == actualAnswer[0][0] );
	TEMPER_CHECK_TRUE( expectedAnswer[0][1] == actualAnswer[0][1] );
	TEMPER_CHECK_TRUE( expectedAnswer[0][2] == actualAnswer[0][2] );

	TEMPER_CHECK_TRUE( expectedAnswer[1][0] == actualAnswer[1][0] );
	TEMPER_CHECK_TRUE( expectedAnswer[1][1] == actualAnswer[1][1] );
	TEMPER_CHECK_TRUE( expectedAnswer[1][2] == actualAnswer[1][2] );

}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_int2x3,
	int2x3(
		0, 0, 0,
		0, 0, 0
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_int2x3,
	int2x3(
		10, 10, 10,
		10, 10, 10
	),
	int2x3(
		10, 10, 10,
		10, 10, 10
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_int2x3,
	int2x3(
		10, 20, 30,
		50, 60, 70
	),
	int2x3(
		10, 20, 30,
		50, 60, 70
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_int2x3,
	int2x3(
		160, 150, 140,
		120, 110, 100
	),
	int2x3(
		160, 150, 140,
		120, 110, 100
	)
);

TEMPER_PARAMETRIC( Test_int2x3_int2x4, TEMPER_FLAG_SHOULD_RUN, const int2x4& convertFrom, const int2x3& expectedAnswer )
{
	int2x3 actualAnswer = int2x3( convertFrom );

	TEMPER_CHECK_TRUE( expectedAnswer[0][0] == actualAnswer[0][0] );
	TEMPER_CHECK_TRUE( expectedAnswer[0][1] == actualAnswer[0][1] );
	TEMPER_CHECK_TRUE( expectedAnswer[0][2] == actualAnswer[0][2] );

	TEMPER_CHECK_TRUE( expectedAnswer[1][0] == actualAnswer[1][0] );
	TEMPER_CHECK_TRUE( expectedAnswer[1][1] == actualAnswer[1][1] );
	TEMPER_CHECK_TRUE( expectedAnswer[1][2] == actualAnswer[1][2] );

}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_int2x4,
	int2x4(
		0, 0, 0, 0,
		0, 0, 0, 0
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_int2x4,
	int2x4(
		10, 10, 10, 10,
		10, 10, 10, 10
	),
	int2x3(
		10, 10, 10,
		10, 10, 10
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_int2x4,
	int2x4(
		10, 20, 30, 40,
		50, 60, 70, 80
	),
	int2x3(
		10, 20, 30,
		50, 60, 70
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_int2x4,
	int2x4(
		160, 150, 140, 130,
		120, 110, 100, 90
	),
	int2x3(
		160, 150, 140,
		120, 110, 100
	)
);

TEMPER_PARAMETRIC( Test_int2x3_uint2x2, TEMPER_FLAG_SHOULD_RUN, const uint2x2& convertFrom, const int2x3& expectedAnswer )
{
	int2x3 actualAnswer = int2x3( convertFrom );

	TEMPER_CHECK_TRUE( expectedAnswer[0][0] == actualAnswer[0][0] );
	TEMPER_CHECK_TRUE( expectedAnswer[0][1] == actualAnswer[0][1] );

	TEMPER_CHECK_TRUE( expectedAnswer[1][0] == actualAnswer[1][0] );
	TEMPER_CHECK_TRUE( expectedAnswer[1][1] == actualAnswer[1][1] );

}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_uint2x2,
	uint2x2(
		0U, 0U,
		0U, 0U
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_uint2x2,
	uint2x2(
		10U, 10U,
		10U, 10U
	),
	int2x3(
		10, 10, 10,
		10, 10, 10
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_uint2x2,
	uint2x2(
		10U, 20U,
		50U, 60U
	),
	int2x3(
		10, 20, 30,
		50, 60, 70
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_uint2x2,
	uint2x2(
		160U, 150U,
		120U, 110U
	),
	int2x3(
		160, 150, 140,
		120, 110, 100
	)
);

TEMPER_PARAMETRIC( Test_int2x3_uint2x3, TEMPER_FLAG_SHOULD_RUN, const uint2x3& convertFrom, const int2x3& expectedAnswer )
{
	int2x3 actualAnswer = int2x3( convertFrom );

	TEMPER_CHECK_TRUE( expectedAnswer[0][0] == actualAnswer[0][0] );
	TEMPER_CHECK_TRUE( expectedAnswer[0][1] == actualAnswer[0][1] );
	TEMPER_CHECK_TRUE( expectedAnswer[0][2] == actualAnswer[0][2] );

	TEMPER_CHECK_TRUE( expectedAnswer[1][0] == actualAnswer[1][0] );
	TEMPER_CHECK_TRUE( expectedAnswer[1][1] == actualAnswer[1][1] );
	TEMPER_CHECK_TRUE( expectedAnswer[1][2] == actualAnswer[1][2] );

}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_uint2x3,
	uint2x3(
		0U, 0U, 0U,
		0U, 0U, 0U
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_uint2x3,
	uint2x3(
		10U, 10U, 10U,
		10U, 10U, 10U
	),
	int2x3(
		10, 10, 10,
		10, 10, 10
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_uint2x3,
	uint2x3(
		10U, 20U, 30U,
		50U, 60U, 70U
	),
	int2x3(
		10, 20, 30,
		50, 60, 70
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_uint2x3,
	uint2x3(
		160U, 150U, 140U,
		120U, 110U, 100U
	),
	int2x3(
		160, 150, 140,
		120, 110, 100
	)
);

TEMPER_PARAMETRIC( Test_int2x3_uint2x4, TEMPER_FLAG_SHOULD_RUN, const uint2x4& convertFrom, const int2x3& expectedAnswer )
{
	int2x3 actualAnswer = int2x3( convertFrom );

	TEMPER_CHECK_TRUE( expectedAnswer[0][0] == actualAnswer[0][0] );
	TEMPER_CHECK_TRUE( expectedAnswer[0][1] == actualAnswer[0][1] );
	TEMPER_CHECK_TRUE( expectedAnswer[0][2] == actualAnswer[0][2] );

	TEMPER_CHECK_TRUE( expectedAnswer[1][0] == actualAnswer[1][0] );
	TEMPER_CHECK_TRUE( expectedAnswer[1][1] == actualAnswer[1][1] );
	TEMPER_CHECK_TRUE( expectedAnswer[1][2] == actualAnswer[1][2] );

}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_uint2x4,
	uint2x4(
		0U, 0U, 0U, 0U,
		0U, 0U, 0U, 0U
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_uint2x4,
	uint2x4(
		10U, 10U, 10U, 10U,
		10U, 10U, 10U, 10U
	),
	int2x3(
		10, 10, 10,
		10, 10, 10
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_uint2x4,
	uint2x4(
		10U, 20U, 30U, 40U,
		50U, 60U, 70U, 80U
	),
	int2x3(
		10, 20, 30,
		50, 60, 70
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_uint2x4,
	uint2x4(
		160U, 150U, 140U, 130U,
		120U, 110U, 100U, 90U
	),
	int2x3(
		160, 150, 140,
		120, 110, 100
	)
);

TEMPER_PARAMETRIC( Test_int2x3_float2x2, TEMPER_FLAG_SHOULD_RUN, const float2x2& convertFrom, const int2x3& expectedAnswer )
{
	int2x3 actualAnswer = int2x3( convertFrom );

	TEMPER_CHECK_TRUE( expectedAnswer[0][0] == actualAnswer[0][0] );
	TEMPER_CHECK_TRUE( expectedAnswer[0][1] == actualAnswer[0][1] );

	TEMPER_CHECK_TRUE( expectedAnswer[1][0] == actualAnswer[1][0] );
	TEMPER_CHECK_TRUE( expectedAnswer[1][1] == actualAnswer[1][1] );

}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_float2x2,
	float2x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_float2x2,
	float2x2(
		10.000000f, 10.000000f,
		10.000000f, 10.000000f
	),
	int2x3(
		10, 10, 10,
		10, 10, 10
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_float2x2,
	float2x2(
		10.000000f, 20.000000f,
		50.000000f, 60.000000f
	),
	int2x3(
		10, 20, 30,
		50, 60, 70
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_float2x2,
	float2x2(
		160.000000f, 150.000000f,
		120.000000f, 110.000000f
	),
	int2x3(
		160, 150, 140,
		120, 110, 100
	)
);

TEMPER_PARAMETRIC( Test_int2x3_float2x3, TEMPER_FLAG_SHOULD_RUN, const float2x3& convertFrom, const int2x3& expectedAnswer )
{
	int2x3 actualAnswer = int2x3( convertFrom );

	TEMPER_CHECK_TRUE( expectedAnswer[0][0] == actualAnswer[0][0] );
	TEMPER_CHECK_TRUE( expectedAnswer[0][1] == actualAnswer[0][1] );
	TEMPER_CHECK_TRUE( expectedAnswer[0][2] == actualAnswer[0][2] );

	TEMPER_CHECK_TRUE( expectedAnswer[1][0] == actualAnswer[1][0] );
	TEMPER_CHECK_TRUE( expectedAnswer[1][1] == actualAnswer[1][1] );
	TEMPER_CHECK_TRUE( expectedAnswer[1][2] == actualAnswer[1][2] );

}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_float2x3,
	float2x3(
		0.000000f, 0.000000f, 0.000000f,
		0.000000f, 0.000000f, 0.000000f
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_float2x3,
	float2x3(
		10.000000f, 10.000000f, 10.000000f,
		10.000000f, 10.000000f, 10.000000f
	),
	int2x3(
		10, 10, 10,
		10, 10, 10
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_float2x3,
	float2x3(
		10.000000f, 20.000000f, 30.000000f,
		50.000000f, 60.000000f, 70.000000f
	),
	int2x3(
		10, 20, 30,
		50, 60, 70
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_float2x3,
	float2x3(
		160.000000f, 150.000000f, 140.000000f,
		120.000000f, 110.000000f, 100.000000f
	),
	int2x3(
		160, 150, 140,
		120, 110, 100
	)
);

TEMPER_PARAMETRIC( Test_int2x3_float2x4, TEMPER_FLAG_SHOULD_RUN, const float2x4& convertFrom, const int2x3& expectedAnswer )
{
	int2x3 actualAnswer = int2x3( convertFrom );

	TEMPER_CHECK_TRUE( expectedAnswer[0][0] == actualAnswer[0][0] );
	TEMPER_CHECK_TRUE( expectedAnswer[0][1] == actualAnswer[0][1] );
	TEMPER_CHECK_TRUE( expectedAnswer[0][2] == actualAnswer[0][2] );

	TEMPER_CHECK_TRUE( expectedAnswer[1][0] == actualAnswer[1][0] );
	TEMPER_CHECK_TRUE( expectedAnswer[1][1] == actualAnswer[1][1] );
	TEMPER_CHECK_TRUE( expectedAnswer[1][2] == actualAnswer[1][2] );

}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_float2x4,
	float2x4(
		0.000000f, 0.000000f, 0.000000f, 0.000000f,
		0.000000f, 0.000000f, 0.000000f, 0.000000f
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_float2x4,
	float2x4(
		10.000000f, 10.000000f, 10.000000f, 10.000000f,
		10.000000f, 10.000000f, 10.000000f, 10.000000f
	),
	int2x3(
		10, 10, 10,
		10, 10, 10
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_float2x4,
	float2x4(
		10.000000f, 20.000000f, 30.000000f, 40.000000f,
		50.000000f, 60.000000f, 70.000000f, 80.000000f
	),
	int2x3(
		10, 20, 30,
		50, 60, 70
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_float2x4,
	float2x4(
		160.000000f, 150.000000f, 140.000000f, 130.000000f,
		120.000000f, 110.000000f, 100.000000f, 90.000000f
	),
	int2x3(
		160, 150, 140,
		120, 110, 100
	)
);

TEMPER_PARAMETRIC( Test_int2x3_double2x2, TEMPER_FLAG_SHOULD_RUN, const double2x2& convertFrom, const int2x3& expectedAnswer )
{
	int2x3 actualAnswer = int2x3( convertFrom );

	TEMPER_CHECK_TRUE( expectedAnswer[0][0] == actualAnswer[0][0] );
	TEMPER_CHECK_TRUE( expectedAnswer[0][1] == actualAnswer[0][1] );

	TEMPER_CHECK_TRUE( expectedAnswer[1][0] == actualAnswer[1][0] );
	TEMPER_CHECK_TRUE( expectedAnswer[1][1] == actualAnswer[1][1] );

}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_double2x2,
	double2x2(
		0.000000f, 0.000000f,
		0.000000f, 0.000000f
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_double2x2,
	double2x2(
		10.000000f, 10.000000f,
		10.000000f, 10.000000f
	),
	int2x3(
		10, 10, 10,
		10, 10, 10
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_double2x2,
	double2x2(
		10.000000f, 20.000000f,
		50.000000f, 60.000000f
	),
	int2x3(
		10, 20, 30,
		50, 60, 70
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_double2x2,
	double2x2(
		160.000000f, 150.000000f,
		120.000000f, 110.000000f
	),
	int2x3(
		160, 150, 140,
		120, 110, 100
	)
);

TEMPER_PARAMETRIC( Test_int2x3_double2x3, TEMPER_FLAG_SHOULD_RUN, const double2x3& convertFrom, const int2x3& expectedAnswer )
{
	int2x3 actualAnswer = int2x3( convertFrom );

	TEMPER_CHECK_TRUE( expectedAnswer[0][0] == actualAnswer[0][0] );
	TEMPER_CHECK_TRUE( expectedAnswer[0][1] == actualAnswer[0][1] );
	TEMPER_CHECK_TRUE( expectedAnswer[0][2] == actualAnswer[0][2] );

	TEMPER_CHECK_TRUE( expectedAnswer[1][0] == actualAnswer[1][0] );
	TEMPER_CHECK_TRUE( expectedAnswer[1][1] == actualAnswer[1][1] );
	TEMPER_CHECK_TRUE( expectedAnswer[1][2] == actualAnswer[1][2] );

}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_double2x3,
	double2x3(
		0.000000f, 0.000000f, 0.000000f,
		0.000000f, 0.000000f, 0.000000f
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_double2x3,
	double2x3(
		10.000000f, 10.000000f, 10.000000f,
		10.000000f, 10.000000f, 10.000000f
	),
	int2x3(
		10, 10, 10,
		10, 10, 10
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_double2x3,
	double2x3(
		10.000000f, 20.000000f, 30.000000f,
		50.000000f, 60.000000f, 70.000000f
	),
	int2x3(
		10, 20, 30,
		50, 60, 70
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_double2x3,
	double2x3(
		160.000000f, 150.000000f, 140.000000f,
		120.000000f, 110.000000f, 100.000000f
	),
	int2x3(
		160, 150, 140,
		120, 110, 100
	)
);

TEMPER_PARAMETRIC( Test_int2x3_double2x4, TEMPER_FLAG_SHOULD_RUN, const double2x4& convertFrom, const int2x3& expectedAnswer )
{
	int2x3 actualAnswer = int2x3( convertFrom );

	TEMPER_CHECK_TRUE( expectedAnswer[0][0] == actualAnswer[0][0] );
	TEMPER_CHECK_TRUE( expectedAnswer[0][1] == actualAnswer[0][1] );
	TEMPER_CHECK_TRUE( expectedAnswer[0][2] == actualAnswer[0][2] );

	TEMPER_CHECK_TRUE( expectedAnswer[1][0] == actualAnswer[1][0] );
	TEMPER_CHECK_TRUE( expectedAnswer[1][1] == actualAnswer[1][1] );
	TEMPER_CHECK_TRUE( expectedAnswer[1][2] == actualAnswer[1][2] );

}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_double2x4,
	double2x4(
		0.000000f, 0.000000f, 0.000000f, 0.000000f,
		0.000000f, 0.000000f, 0.000000f, 0.000000f
	),
	int2x3(
		0, 0, 0,
		0, 0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_double2x4,
	double2x4(
		10.000000f, 10.000000f, 10.000000f, 10.000000f,
		10.000000f, 10.000000f, 10.000000f, 10.000000f
	),
	int2x3(
		10, 10, 10,
		10, 10, 10
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_double2x4,
	double2x4(
		10.000000f, 20.000000f, 30.000000f, 40.000000f,
		50.000000f, 60.000000f, 70.000000f, 80.000000f
	),
	int2x3(
		10, 20, 30,
		50, 60, 70
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_double2x4,
	double2x4(
		160.000000f, 150.000000f, 140.000000f, 130.000000f,
		120.000000f, 110.000000f, 100.000000f, 90.000000f
	),
	int2x3(
		160, 150, 140,
		120, 110, 100
	)
);

TEMPER_PARAMETRIC( Test_int2x3_identity, TEMPER_FLAG_SHOULD_RUN, const int2x3& matrix, const bool expectedAnswer )
{
	int2x3 identityMat;
	identity( identityMat );
	bool isMatrixIdentity = ( identityMat == matrix );
	TEMPER_CHECK_TRUE( isMatrixIdentity == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_identity,
	int2x3(
		1, 0, 0,
		0, 1, 0
	),
	true
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_identity,
	int2x3(
		1, 1, 0,
		0, 1, 0
	),
	false
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_identity,
	int2x3(
		1, 0, 0,
		1, 1, 0
	),
	false
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_identity,
	int2x3(
		1, 1, 0,
		1, 1, 0
	),
	false
);

TEMPER_PARAMETRIC( Test_int2x3_transpose, TEMPER_FLAG_SHOULD_RUN, const int2x3& matrix, const int3x2& expectedAnswer )
{
	int3x2 actualResult = transpose( matrix );
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_transpose,
	int2x3(
		1, 0, 0,
		0, 1, 0
	),
	int3x2(
		1, 0,
		0, 1,
		0, 0
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_transpose,
	int2x3(
		0, 1, 2,
		4, 5, 6
	),
	int3x2(
		0, 4,
		1, 5,
		2, 6
	)
);

TEMPER_PARAMETRIC( Test_int2x3_mulm, TEMPER_FLAG_SHOULD_RUN, const int2x3& lhs, const int3x2& rhs, const int2x2& expectedAnswer )
{
	int2x2 actualResult = mul( lhs, rhs );
	TEMPER_CHECK_TRUE( actualResult == expectedAnswer );
}

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_mulm,
	int2x3(
		2, 2, 2,
		2, 2, 2
	),
	int3x2(
		4, 4,
		4, 4,
		4, 4
	),
	int2x2(
		24, 24,
		24, 24
	)
);

TEMPER_INVOKE_PARAMETRIC_TEST( Test_int2x3_mulm,
	int2x3(
		2, 2, 2,
		2, 2, 2
	),
	int3x2(
		1, 0,
		0, 1,
		0, 0
	),
	int2x2(
		2, 2,
		2, 2
	)
);

