/*
===========================================================================

HLML.

MIT License

Copyright (c) 2019 Dan Moody

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

===========================================================================
*/

// THIS FILE WAS AUTOMATICALLY GENERATED BY A TOOL.
// EDITING THIS FILE MAY CAUSE SIDE EFFECTS.
// DO SO AT YOUR OWN RISK.

TEMPER_TEST( TestAssignment_uint2, TEMPER_FLAG_SHOULD_RUN )
{
	uint2 vec;

	vec.x = 1U;
	vec.y = 1U;
	TEMPER_CHECK_TRUE( vec.x == 1U );
	TEMPER_CHECK_TRUE( vec.y == 1U );

	vec.x = 0U;
	vec.y = 1U;
	TEMPER_CHECK_TRUE( vec.x == 0U );
	TEMPER_CHECK_TRUE( vec.y == 1U );
}

TEMPER_TEST( TestArithmeticAddition_uint2, TEMPER_FLAG_SHOULD_RUN )
{
	uint2 a = (uint2)	{ 6U, 6U };
	uint2 b = (uint2)	{ 2U, 3U };
	uint2 c = uint2_caddv( &a, &b );

	TEMPER_CHECK_TRUE( c.x == 8U );
	TEMPER_CHECK_TRUE( c.y == 9U );
}

TEMPER_TEST( TestArithmeticSubtraction_uint2, TEMPER_FLAG_SHOULD_RUN )
{
	uint2 a = (uint2)	{ 6U, 6U };
	uint2 b = (uint2)	{ 2U, 3U };
	uint2 c = uint2_csubv( &a, &b );

	TEMPER_CHECK_TRUE( c.x == 4U );
	TEMPER_CHECK_TRUE( c.y == 3U );
}

TEMPER_TEST( TestArithmeticMultiplication_uint2, TEMPER_FLAG_SHOULD_RUN )
{
	uint2 a = (uint2)	{ 6U, 6U };
	uint2 b = (uint2)	{ 2U, 3U };
	uint2 c = uint2_cmulv( &a, &b );

	TEMPER_CHECK_TRUE( c.x == 12U );
	TEMPER_CHECK_TRUE( c.y == 18U );
}

TEMPER_TEST( TestArithmeticDivision_uint2, TEMPER_FLAG_SHOULD_RUN )
{
	uint2 a = (uint2)	{ 6U, 6U };
	uint2 b = (uint2)	{ 2U, 2U };
	uint2 c = uint2_cdivv( &a, &b );

	TEMPER_CHECK_TRUE( c.x == 3U );
	TEMPER_CHECK_TRUE( c.y == 3U );
}

TEMPER_TEST( TestRelational_uint2, TEMPER_FLAG_SHOULD_RUN )
{
	uint2 vec0 =	{ 0U, 0U };
	uint2 vec1 =	{ 1U, 1U };
	uint2 vec2 =	{ 2U, 2U };
	uint2 vec3 =	{ 3U, 3U };

	bool2 test0  = uint2_cmple( &vec0, &vec0 );
	bool2 test1  = uint2_cmpge( &vec0, &vec0 );
	bool2 test2  = uint2_cmpl( &vec0, &vec1 );
	bool2 test3  = uint2_cmpl( &vec0, &vec2 );
	bool2 test4  = uint2_cmpl( &vec0, &vec3 );

	bool2 test5  = uint2_cmpg( &vec1, &vec0 );
	bool2 test6  = uint2_cmple( &vec1, &vec1 );
	bool2 test7  = uint2_cmpge( &vec1, &vec1 );
	bool2 test8  = uint2_cmpl( &vec1, &vec2 );
	bool2 test9  = uint2_cmpl( &vec1, &vec3 );

	bool2 test10 = uint2_cmpg( &vec2, &vec0 );
	bool2 test11 = uint2_cmpg( &vec2, &vec1 );
	bool2 test12 = uint2_cmple( &vec2, &vec2 );
	bool2 test13 = uint2_cmpge( &vec2, &vec2 );
	bool2 test14 = uint2_cmpl( &vec2, &vec3 );

	bool2 test15 = uint2_cmpg( &vec3, &vec0 );
	bool2 test16 = uint2_cmpg( &vec3, &vec1 );
	bool2 test17 = uint2_cmpg( &vec3, &vec2 );
	bool2 test18 = uint2_cmple( &vec3, &vec3 );
	bool2 test19 = uint2_cmpge( &vec3, &vec3 );

	TEMPER_CHECK_TRUE( bool2_all( &test0 ) );
	TEMPER_CHECK_TRUE( bool2_all( &test1 ) );
	TEMPER_CHECK_TRUE( bool2_all( &test2 ) );
	TEMPER_CHECK_TRUE( bool2_all( &test3 ) );
	TEMPER_CHECK_TRUE( bool2_all( &test4 ) );

	TEMPER_CHECK_TRUE( bool2_all( &test5 ) );
	TEMPER_CHECK_TRUE( bool2_all( &test6 ) );
	TEMPER_CHECK_TRUE( bool2_all( &test7 ) );
	TEMPER_CHECK_TRUE( bool2_all( &test8 ) );
	TEMPER_CHECK_TRUE( bool2_all( &test9 ) );

	TEMPER_CHECK_TRUE( bool2_all( &test10 ) );
	TEMPER_CHECK_TRUE( bool2_all( &test11 ) );
	TEMPER_CHECK_TRUE( bool2_all( &test12 ) );
	TEMPER_CHECK_TRUE( bool2_all( &test13 ) );
	TEMPER_CHECK_TRUE( bool2_all( &test14 ) );

	TEMPER_CHECK_TRUE( bool2_all( &test15 ) );
	TEMPER_CHECK_TRUE( bool2_all( &test16 ) );
	TEMPER_CHECK_TRUE( bool2_all( &test17 ) );
	TEMPER_CHECK_TRUE( bool2_all( &test18 ) );
	TEMPER_CHECK_TRUE( bool2_all( &test19 ) );
}

TEMPER_TEST( TestBitwise_And_uint2, TEMPER_FLAG_SHOULD_RUN )
{
	uint2 answer = (uint2) { 5U, 5U };

	uint2 a = (uint2) { 21U, 21U };
	uint2 b = (uint2) { 7U, 7U };

	uint2 c = uint2_cand( &a, &b );

	TEMPER_CHECK_TRUE( uint2_cmpe( &c, &answer ) );
}

TEMPER_TEST( TestBitwise_Or_uint2, TEMPER_FLAG_SHOULD_RUN )
{
	uint2 answer = (uint2) { 23U, 23U };

	uint2 a = (uint2) { 21U, 21U };
	uint2 b = (uint2) { 7U, 7U };

	uint2 c = uint2_cor( &a, &b );

	TEMPER_CHECK_TRUE( uint2_cmpe( &c, &answer ) );
}

TEMPER_TEST( TestBitwise_Xor_uint2, TEMPER_FLAG_SHOULD_RUN )
{
	uint2 answer = (uint2) { 18U, 18U };

	uint2 a = (uint2) { 21U, 21U };
	uint2 b = (uint2) { 7U, 7U };

	uint2 c = uint2_cxor( &a, &b );

	TEMPER_CHECK_TRUE( uint2_cmpe( &c, &answer ) );
}

TEMPER_TEST( TestBitwise_ShiftLeft_uint2, TEMPER_FLAG_SHOULD_RUN )
{
	uint2 answer = (uint2) { 4U, 4U };

	uint2 a = (uint2) { 1U, 1U };
	uint2 b = (uint2) { 2U, 2U };

	uint2 c = uint2_cshift_left( &a, &b );

	TEMPER_CHECK_TRUE( uint2_cmpe( &c, &answer ) );
}

TEMPER_TEST( TestBitwise_ShiftRight_uint2, TEMPER_FLAG_SHOULD_RUN )
{
	uint2 answer = (uint2) { 1U, 1U };

	uint2 a = (uint2) { 16U, 16U };
	uint2 b = (uint2) { 4U, 4U };

	uint2 c = uint2_cshift_right( &a, &b );

	TEMPER_CHECK_TRUE( uint2_cmpe( &c, &answer ) );
}

TEMPER_TEST( TestBitwise_Unary_uint2, TEMPER_FLAG_SHOULD_RUN )
{
	uint2 answer = (uint2) { (uint32_t) -1, (uint32_t) -1 };

	uint2 a = (uint2) { 0U, 0U };

	uint2 b = uint2_cunary( &a );

	TEMPER_CHECK_TRUE( uint2_cmpe( &b, &answer ) );
}

TEMPER_TEST( TestLength_Scalar_uint2, TEMPER_FLAG_SHOULD_RUN )
{
	uint2 vec = (uint2) { 2U, 2U };

	TEMPER_CHECK_TRUE( floateq( uint2_lengthsqr( &vec ), 8.0f ) );
	TEMPER_CHECK_TRUE( floateq( uint2_length( &vec ), 2.82842712475f ) );
}

TEMPER_TEST( TestDistance_Scalar_uint2, TEMPER_FLAG_SHOULD_RUN )
{
	float answerDistanceSqr = 104.0f;
	float answerDistance    = 10.198039f;

	uint2 a = (uint2) { 7U, 4U };
	uint2 b = (uint2) { 17U, 6U };

	float distSqr = uint2_distancesqr( &a, &b );
	float dist    = uint2_distance( &a, &b );

	TEMPER_CHECK_TRUE( floateq( distSqr, answerDistanceSqr ) );
	TEMPER_CHECK_TRUE( floateq( dist, answerDistance ) );
}

