/*
===========================================================================

HLML.

MIT License

Copyright (c) 2019 Dan Moody

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

===========================================================================
*/

// THIS FILE WAS AUTOMATICALLY GENERATED BY A TOOL.
// EDITING THIS FILE MAY CAUSE SIDE EFFECTS.
// DO SO AT YOUR OWN RISK.

#pragma once

struct bool2;
struct bool3;
struct bool4;

struct bool3_swizzle_3_to_2_xx_t
{
	bool32_t v[3];

	HLML_INLINE operator bool2() const;
};

struct bool3_swizzle_3_to_2_yx_t
{
	bool32_t v[3];

	HLML_INLINE bool2 operator=( const bool2& vec );

	HLML_INLINE operator bool2() const;
};

struct bool3_swizzle_3_to_2_zx_t
{
	bool32_t v[3];

	HLML_INLINE bool2 operator=( const bool2& vec );

	HLML_INLINE operator bool2() const;
};

struct bool3_swizzle_3_to_2_xy_t
{
	bool32_t v[3];

	HLML_INLINE bool2 operator=( const bool2& vec );

	HLML_INLINE operator bool2() const;
};

struct bool3_swizzle_3_to_2_yy_t
{
	bool32_t v[3];

	HLML_INLINE operator bool2() const;
};

struct bool3_swizzle_3_to_2_zy_t
{
	bool32_t v[3];

	HLML_INLINE bool2 operator=( const bool2& vec );

	HLML_INLINE operator bool2() const;
};

struct bool3_swizzle_3_to_2_xz_t
{
	bool32_t v[3];

	HLML_INLINE bool2 operator=( const bool2& vec );

	HLML_INLINE operator bool2() const;
};

struct bool3_swizzle_3_to_2_yz_t
{
	bool32_t v[3];

	HLML_INLINE bool2 operator=( const bool2& vec );

	HLML_INLINE operator bool2() const;
};

struct bool3_swizzle_3_to_2_zz_t
{
	bool32_t v[3];

	HLML_INLINE operator bool2() const;
};

struct bool3_swizzle_3_to_3_xxx_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_yxx_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_zxx_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_xyx_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_yyx_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_zyx_t
{
	bool32_t v[3];

	HLML_INLINE bool3 operator=( const bool3& vec );

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_xzx_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_yzx_t
{
	bool32_t v[3];

	HLML_INLINE bool3 operator=( const bool3& vec );

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_zzx_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_xxy_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_yxy_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_zxy_t
{
	bool32_t v[3];

	HLML_INLINE bool3 operator=( const bool3& vec );

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_xyy_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_yyy_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_zyy_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_xzy_t
{
	bool32_t v[3];

	HLML_INLINE bool3 operator=( const bool3& vec );

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_yzy_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_zzy_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_xxz_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_yxz_t
{
	bool32_t v[3];

	HLML_INLINE bool3 operator=( const bool3& vec );

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_zxz_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_xyz_t
{
	bool32_t v[3];

	HLML_INLINE bool3 operator=( const bool3& vec );

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_yyz_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_zyz_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_xzz_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_yzz_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_zzz_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_4_xxxx_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_yxxx_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_zxxx_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_xyxx_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_yyxx_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_zyxx_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_xzxx_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_yzxx_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_zzxx_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_xxyx_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_yxyx_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_zxyx_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_xyyx_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_yyyx_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_zyyx_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_xzyx_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_yzyx_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_zzyx_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_xxzx_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_yxzx_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_zxzx_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_xyzx_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_yyzx_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_zyzx_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_xzzx_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_yzzx_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_zzzx_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_xxxy_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_yxxy_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_zxxy_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_xyxy_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_yyxy_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_zyxy_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_xzxy_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_yzxy_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_zzxy_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_xxyy_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_yxyy_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_zxyy_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_xyyy_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_yyyy_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_zyyy_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_xzyy_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_yzyy_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_zzyy_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_xxzy_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_yxzy_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_zxzy_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_xyzy_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_yyzy_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_zyzy_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_xzzy_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_yzzy_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_zzzy_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_xxxz_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_yxxz_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_zxxz_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_xyxz_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_yyxz_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_zyxz_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_xzxz_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_yzxz_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_zzxz_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_xxyz_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_yxyz_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_zxyz_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_xyyz_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_yyyz_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_zyyz_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_xzyz_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_yzyz_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_zzyz_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_xxzz_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_yxzz_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_zxzz_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_xyzz_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_yyzz_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_zyzz_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_xzzz_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_yzzz_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_zzzz_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_2_rr_t
{
	bool32_t v[3];

	HLML_INLINE operator bool2() const;
};

struct bool3_swizzle_3_to_2_gr_t
{
	bool32_t v[3];

	HLML_INLINE bool2 operator=( const bool2& vec );

	HLML_INLINE operator bool2() const;
};

struct bool3_swizzle_3_to_2_br_t
{
	bool32_t v[3];

	HLML_INLINE bool2 operator=( const bool2& vec );

	HLML_INLINE operator bool2() const;
};

struct bool3_swizzle_3_to_2_rg_t
{
	bool32_t v[3];

	HLML_INLINE bool2 operator=( const bool2& vec );

	HLML_INLINE operator bool2() const;
};

struct bool3_swizzle_3_to_2_gg_t
{
	bool32_t v[3];

	HLML_INLINE operator bool2() const;
};

struct bool3_swizzle_3_to_2_bg_t
{
	bool32_t v[3];

	HLML_INLINE bool2 operator=( const bool2& vec );

	HLML_INLINE operator bool2() const;
};

struct bool3_swizzle_3_to_2_rb_t
{
	bool32_t v[3];

	HLML_INLINE bool2 operator=( const bool2& vec );

	HLML_INLINE operator bool2() const;
};

struct bool3_swizzle_3_to_2_gb_t
{
	bool32_t v[3];

	HLML_INLINE bool2 operator=( const bool2& vec );

	HLML_INLINE operator bool2() const;
};

struct bool3_swizzle_3_to_2_bb_t
{
	bool32_t v[3];

	HLML_INLINE operator bool2() const;
};

struct bool3_swizzle_3_to_3_rrr_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_grr_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_brr_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_rgr_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_ggr_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_bgr_t
{
	bool32_t v[3];

	HLML_INLINE bool3 operator=( const bool3& vec );

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_rbr_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_gbr_t
{
	bool32_t v[3];

	HLML_INLINE bool3 operator=( const bool3& vec );

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_bbr_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_rrg_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_grg_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_brg_t
{
	bool32_t v[3];

	HLML_INLINE bool3 operator=( const bool3& vec );

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_rgg_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_ggg_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_bgg_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_rbg_t
{
	bool32_t v[3];

	HLML_INLINE bool3 operator=( const bool3& vec );

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_gbg_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_bbg_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_rrb_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_grb_t
{
	bool32_t v[3];

	HLML_INLINE bool3 operator=( const bool3& vec );

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_brb_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_rgb_t
{
	bool32_t v[3];

	HLML_INLINE bool3 operator=( const bool3& vec );

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_ggb_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_bgb_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_rbb_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_gbb_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_3_bbb_t
{
	bool32_t v[3];

	HLML_INLINE operator bool3() const;
};

struct bool3_swizzle_3_to_4_rrrr_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_grrr_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_brrr_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_rgrr_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_ggrr_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_bgrr_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_rbrr_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_gbrr_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_bbrr_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_rrgr_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_grgr_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_brgr_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_rggr_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_gggr_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_bggr_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_rbgr_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_gbgr_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_bbgr_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_rrbr_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_grbr_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_brbr_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_rgbr_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_ggbr_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_bgbr_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_rbbr_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_gbbr_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_bbbr_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_rrrg_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_grrg_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_brrg_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_rgrg_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_ggrg_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_bgrg_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_rbrg_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_gbrg_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_bbrg_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_rrgg_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_grgg_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_brgg_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_rggg_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_gggg_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_bggg_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_rbgg_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_gbgg_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_bbgg_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_rrbg_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_grbg_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_brbg_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_rgbg_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_ggbg_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_bgbg_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_rbbg_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_gbbg_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_bbbg_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_rrrb_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_grrb_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_brrb_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_rgrb_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_ggrb_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_bgrb_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_rbrb_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_gbrb_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_bbrb_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_rrgb_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_grgb_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_brgb_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_rggb_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_gggb_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_bggb_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_rbgb_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_gbgb_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_bbgb_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_rrbb_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_grbb_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_brbb_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_rgbb_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_ggbb_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_bgbb_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_rbbb_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_gbbb_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

struct bool3_swizzle_3_to_4_bbbb_t
{
	bool32_t v[3];

	HLML_INLINE operator bool4() const;
};

