// THIS FILE WAS AUTOMATICALLY GENERATED BY A TOOL.
// EDITING THIS FILE MAY CAUSE SIDE EFFECTS.
// DO SO AT YOUR OWN RISK.

#pragma once

#ifdef HLML_NAMESPACE
namespace hlml
{
#endif

#include "double4.h"

#include "hlml_defines.h"

double4::double4( const double scalar )
	: x( scalar )
	, y( scalar )
	, z( scalar )
	, w( scalar )
{
}

double4::double4( const double x, const double y, const double z, const double w )
	: x( x )
	, y( y )
	, z( z )
	, w( w )
{
}

double4::double4( const double4 &vec )
	: x( vec.x )
	, y( vec.y )
	, z( vec.z )
	, w( vec.w )
{
}

double4::double4( const bool4 &vec )
	: x( (double) vec.x )
	, y( (double) vec.y )
	, z( (double) vec.z )
	, w( (double) vec.w )
{
}

double4::double4( const int4 &vec )
	: x( (double) vec.x )
	, y( (double) vec.y )
	, z( (double) vec.z )
	, w( (double) vec.w )
{
}

double4::double4( const uint4 &vec )
	: x( (double) vec.x )
	, y( (double) vec.y )
	, z( (double) vec.z )
	, w( (double) vec.w )
{
}

double4::double4( const float4 &vec )
	: x( (double) vec.x )
	, y( (double) vec.y )
	, z( (double) vec.z )
	, w( (double) vec.w )
{
}

double4::double4( const double2 &xy, const double z, const double w )
	: x( xy.x )
	, y( xy.y )
	, z( z )
	, w( w )
{
}

double4::double4( const double x, const double y, const double2 &zw )
	: x( x )
	, y( y )
	, z( zw.x )
	, w( zw.y )
{
}

double4::double4( const double3 &xyz, const double w )
	: x( xyz.x )
	, y( xyz.y )
	, z( xyz.z )
	, w( w )
{
}

double4::double4( const double x, const double3 &w )
	: x( x )
	, y( w.x )
	, z( w.y )
	, w( w.z )
{
}

double4::double4( const double2 &xy, const double2 &zw )
	: x( xy.x )
	, y( xy.y )
	, z( zw.x )
	, w( zw.y )
{
}

double4 double4::operator=( const double2 &other )
{
	this->x = other.x;
	this->y = other.y;

	return *this;
}

double4 double4::operator=( const double3 &other )
{
	this->x = other.x;
	this->y = other.y;
	this->z = other.z;

	return *this;
}

double4 double4::operator=( const double4 &other )
{
	this->x = other.x;
	this->y = other.y;
	this->z = other.z;
	this->w = other.w;

	return *this;
}

double &double4::operator[]( const int32_t index )
{
	HLML_ASSERT( index >= 0 && index < 4 );
	return v[index];
}

const double &double4::operator[]( const int32_t index ) const
{
	HLML_ASSERT( index >= 0 && index < 4 );
	return v[index];
}
#ifdef HLML_NAMESPACE
}
#endif
