// This file was automatically generated by HLML v3.0.0.
// Editing this file may cause side effects.

#pragma once

#ifdef HLML_NAMESPACE
namespace hlml
{
#endif

#include "double3.h"

#include "hlml_defines.h"

double3::double3( const double scalar )
	: x( scalar )
	, y( scalar )
	, z( scalar )
{
}

double3::double3( const double x, const double y, const double z )
	: x( x )
	, y( y )
	, z( z )
{
}

double3::double3( const double3 &vec )
	: x( vec.x )
	, y( vec.y )
	, z( vec.z )
{
}

double3::double3( const bool3 &vec )
	: x( (double) vec.x )
	, y( (double) vec.y )
	, z( (double) vec.z )
{
}

double3::double3( const int3 &vec )
	: x( (double) vec.x )
	, y( (double) vec.y )
	, z( (double) vec.z )
{
}

double3::double3( const uint3 &vec )
	: x( (double) vec.x )
	, y( (double) vec.y )
	, z( (double) vec.z )
{
}

double3::double3( const float3 &vec )
	: x( (double) vec.x )
	, y( (double) vec.y )
	, z( (double) vec.z )
{
}

double3::double3( const double2 &xy, const double z )
	: x( xy.x )
	, y( xy.y )
	, z( z )
{
}

double3::double3( const double x, const double2 &zw )
	: x( x )
	, y( zw.x )
	, z( zw.y )
{
}

double3 double3::operator=( const double2 &other )
{
	this->x = other.x;
	this->y = other.y;

	return *this;
}

double3 double3::operator=( const double3 &other )
{
	this->x = other.x;
	this->y = other.y;
	this->z = other.z;

	return *this;
}

double &double3::operator[]( const int32_t index )
{
	HLML_ASSERT( index >= 0 && index < 3 );
	return v[index];
}

const double &double3::operator[]( const int32_t index ) const
{
	HLML_ASSERT( index >= 0 && index < 3 );
	return v[index];
}
#ifdef HLML_NAMESPACE
}
#endif
