// THIS FILE WAS AUTOMATICALLY GENERATED BY A TOOL.
// EDITING THIS FILE MAY CAUSE SIDE EFFECTS.
// DO SO AT YOUR OWN RISK.

#pragma once

#ifdef __cplusplus
#define HLML_CONSTRUCT( type ) type
#else
#define HLML_CONSTRUCT( type ) (type)
#endif

#ifndef HLML_ASSERT
#include <assert.h>
#define HLML_ASSERT assert
#endif

#ifndef HLML_INLINE
// GCC inline semantics for C99 dont work the same way other compilers
// https://gcc.gnu.org/gcc-5/porting_to.html
#if !defined( __cplusplus ) && defined( __GNUC__ )
#define HLML_INLINE extern inline
#else
#define HLML_INLINE inline
#endif
#endif

