// THIS FILE WAS AUTOMATICALLY GENERATED BY A TOOL.
// EDITING THIS FILE MAY CAUSE SIDE EFFECTS.
// DO SO AT YOUR OWN RISK.

#pragma once

#ifdef HLML_NAMESPACE
namespace hlml
{
#endif

#include "uint4.h"

#include "hlml_defines.h"

uint4::uint4( const uint32_t scalar )
	: x( scalar )
	, y( scalar )
	, z( scalar )
	, w( scalar )
{
}

uint4::uint4( const uint32_t x, const uint32_t y, const uint32_t z, const uint32_t w )
	: x( x )
	, y( y )
	, z( z )
	, w( w )
{
}

uint4::uint4( const uint4& vec )
	: x( vec.x )
	, y( vec.y )
	, z( vec.z )
	, w( vec.w )
{
}

uint4::uint4( const bool4& vec )
	: x( (uint32_t) vec.x )
	, y( (uint32_t) vec.y )
	, z( (uint32_t) vec.z )
	, w( (uint32_t) vec.w )
{
}

uint4::uint4( const int4& vec )
	: x( (uint32_t) vec.x )
	, y( (uint32_t) vec.y )
	, z( (uint32_t) vec.z )
	, w( (uint32_t) vec.w )
{
}

uint4::uint4( const float4& vec )
	: x( (uint32_t) vec.x )
	, y( (uint32_t) vec.y )
	, z( (uint32_t) vec.z )
	, w( (uint32_t) vec.w )
{
}

uint4::uint4( const double4& vec )
	: x( (uint32_t) vec.x )
	, y( (uint32_t) vec.y )
	, z( (uint32_t) vec.z )
	, w( (uint32_t) vec.w )
{
}

uint4::uint4( const uint2& xy, const uint32_t z, const uint32_t w )
	: x( xy.x )
	, y( xy.y )
	, z( z )
	, w( w )
{
}

uint4::uint4( const uint32_t x, const uint32_t y, const uint2& zw )
	: x( x )
	, y( y )
	, z( zw.x )
	, w( zw.y )
{
}

uint4::uint4( const uint3& xyz, const uint32_t w )
	: x( xyz.x )
	, y( xyz.y )
	, z( xyz.z )
	, w( w )
{
}

uint4::uint4( const uint32_t x, const uint3& w )
	: x( x )
	, y( w.x )
	, z( w.y )
	, w( w.z )
{
}

uint4::uint4( const uint2& xy, const uint2& zw )
	: x( xy.x )
	, y( xy.y )
	, z( zw.x )
	, w( zw.y )
{
}

uint4 uint4::operator=( const uint2& other )
{
	this->x = other.x;
	this->y = other.y;

	return *this;
}

uint4 uint4::operator=( const uint3& other )
{
	this->x = other.x;
	this->y = other.y;
	this->z = other.z;

	return *this;
}

uint4 uint4::operator=( const uint4& other )
{
	this->x = other.x;
	this->y = other.y;
	this->z = other.z;
	this->w = other.w;

	return *this;
}

uint32_t& uint4::operator[]( const int32_t index )
{
	HLML_ASSERT( index >= 0 && index < 4 );
	return v[index];
}

const uint32_t& uint4::operator[]( const int32_t index ) const
{
	HLML_ASSERT( index >= 0 && index < 4 );
	return v[index];
}
#ifdef HLML_NAMESPACE
}
#endif
